<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="PacmanGoAugmented" nsURI="http://www.zadahmad.org/dsmcompare/PacmanGoAugmented"
    nsPrefix="PacmanGoAugmented">
  <eClassifiers xsi:type="ecore:EClass" name="GridNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="up" eType="#//GridNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bottom" eType="#//GridNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//GridNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//GridNode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffup" upperBound="2"
        eType="#//DiffGridNode_up" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffbottom" upperBound="2"
        eType="#//DiffGridNode_bottom" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffleft" upperBound="2"
        eType="#//DiffGridNode_left" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffright" upperBound="2"
        eType="#//DiffGridNode_right" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pellet" eSuperTypes="#//PositionableEntity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pacman" eSuperTypes="#//PositionableEntity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Ghost" eSuperTypes="#//PositionableEntity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Scoreboard">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Root">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gn" upperBound="-1" eType="#//GridNode"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sb" lowerBound="1" eType="#//Scoreboard"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" upperBound="-1"
        eType="#//PositionableEntity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainspecificdiffs" upperBound="-1"
        eType="#//DomainSpecificDiff" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PositionableEntity" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="on" lowerBound="1" eType="#//GridNode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffon" upperBound="2"
        eType="#//DiffPositionableEntity_on" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ClassOp">
    <eLiterals name="ADD" literal="ADD"/>
    <eLiterals name="DELETE" value="1" literal="DELETE"/>
    <eLiterals name="MODIFY" value="2" literal="MODIFY"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AscOp">
    <eLiterals name="ADD" literal="ADD"/>
    <eLiterals name="DELETE" value="1" literal="DELETE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffGridNode" eSuperTypes="#//GridNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="post_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffGridNode_up">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//GridNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffGridNode_bottom">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//GridNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffGridNode_left">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//GridNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffGridNode_right">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//GridNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffPellet" eSuperTypes="#//Pellet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="post_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffPacman" eSuperTypes="#//Pacman">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="post_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffGhost" eSuperTypes="#//Ghost">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="post_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffScoreboard" eSuperTypes="#//Scoreboard">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="post_score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="post_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffPositionableEntity_on">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//GridNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainSpecificDiff" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MoveUp" eSuperTypes="#//DomainSpecificDiff">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ghost" lowerBound="1" eType="#//Ghost"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GhostKillingPacman" eSuperTypes="#//DomainSpecificDiff">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ghost" lowerBound="1" eType="#//Ghost"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delpacman" lowerBound="1"
        eType="#//DiffPacman"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PacmanEatingPellet" eSuperTypes="#//DomainSpecificDiff">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pacman" lowerBound="1"
        eType="#//Pacman"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delpelle" lowerBound="1"
        eType="#//DiffPellet"/>
  </eClassifiers>
</ecore:EPackage>
