<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="deleteGame_gridnodes_deleteGame_gridnodes" nsURI="http://cdapackage/deleteGame_gridnodes/deleteGame_gridnodes/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#n1_n1:DiffGame_gridnodes#"/>
  </ecore:EPackage>
  <ecore:EPackage name="deleteGame_gridnodes_deleteGame_gridnodes" nsURI="http://cdapackage/deleteGame_gridnodes/deleteGame_gridnodes/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#n1_n1:DiffGame_gridnodes#"/>
  </ecore:EPackage>
</xmi:XMI>
