<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="petrinetsDiffMM_jot" nsURI="www.geodes.UdeM.edu/petrinetsDiffMM_jot"
    nsPrefix="petrinetsDiffMM_jot">
  <eClassifiers xsi:type="ecore:EEnum" name="AUTHOR">
    <eLiterals name="NIL" literal="NIL"/>
    <eLiterals name="LEFT" value="1" literal="LEFT"/>
    <eLiterals name="RIGHT" value="2" literal="RIGHT"/>
    <eLiterals name="BOTH" value="3" literal="BOTH"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConflictKind">
    <eLiterals name="NIL" literal="NIL"/>
    <eLiterals name="EQUIVALENT" value="1" literal="EQUIVALENT"/>
    <eLiterals name="CONTRADICTING" value="2" literal="CONTRADICTING"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DiffKind">
    <eLiterals name="NIL" literal="NIL"/>
    <eLiterals name="ADD" value="1" literal="ADD"/>
    <eLiterals name="DELETE" value="2" literal="DELETE"/>
    <eLiterals name="MODIFY" value="3" literal="MODIFY"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffPlace" eSuperTypes="#//Place">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conflictKind" unique="false"
        lowerBound="1" eType="#//ConflictKind" defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diffKind" unique="false"
        lowerBound="1" upperBound="2" eType="#//DiffKind" defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameConflictKind" unique="false"
        lowerBound="1" eType="#//ConflictKind" defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_name" unique="false"
        lowerBound="1" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_tokens" unique="false"
        lowerBound="1" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tokensConflictKind" unique="false"
        lowerBound="1" eType="#//ConflictKind" defaultValueLiteral="NIL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffPlace_transitions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conflictGroup" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conflictKind" unique="false"
        lowerBound="1" eType="#//ConflictKind" defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diffKind" unique="false"
        lowerBound="1" upperBound="2" eType="#//DiffKind" defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Transition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetCA" eType="#//Transition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffTransition" eSuperTypes="#//Transition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conflictKind" unique="false"
        lowerBound="1" eType="#//ConflictKind" defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diffKind" unique="false"
        lowerBound="1" upperBound="2" eType="#//DiffKind" defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameConflictKind" unique="false"
        lowerBound="1" eType="#//ConflictKind" defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_name" unique="false"
        lowerBound="1" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffTransition_places">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conflictGroup" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conflictKind" unique="false"
        lowerBound="1" eType="#//ConflictKind" defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diffKind" unique="false"
        lowerBound="1" upperBound="2" eType="#//DiffKind" defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//Place"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetCA" eType="#//Place"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Place" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tokens" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
        eType="#//Transition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="difftransitions" upperBound="-1"
        eType="#//DiffPlace_transitions" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="places" upperBound="-1"
        eType="#//Place"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffplaces" upperBound="-1"
        eType="#//DiffTransition_places" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SemanticConflict" eSuperTypes="#//SemanticObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="semanticdiffs" ordered="false"
        upperBound="-1" eType="#//SemanticDiff"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SemanticDiff" eSuperTypes="#//SemanticObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" unique="false"
        lowerBound="1" eType="#//AUTHOR" defaultValueLiteral="NIL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SemanticObject" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffPlace_transitions"
        ordered="false" upperBound="-1" eType="#//DiffPlace_transitions"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffTransition_places"
        ordered="false" upperBound="-1" eType="#//DiffTransition_places"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_NamedElement"
        ordered="false" upperBound="-1" eType="#//NamedElement"/>
  </eClassifiers>
</ecore:EPackage>
