<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="PacmanDSDiffMM3WayJOT" nsURI="http://www.zadahmad.org/dsmcompare/PacmanDSDiffMM3WayJOT"
    nsPrefix="PacmanDSDiffMM3WayJOT">
  <eClassifiers xsi:type="ecore:EClass" name="GridNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="up" eType="#//GridNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="down" eType="#//GridNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//GridNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//GridNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Food" eSuperTypes="#//PositionableEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lives" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gridnodes" upperBound="-1"
        eType="#//GridNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semanticobjects" upperBound="-1"
        eType="#//SemanticObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffentities" upperBound="-1"
        eType="#//DiffGame_entities" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//PositionableEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Energizer" eSuperTypes="#//Food">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="durations" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DiffKind">
    <eLiterals name="ADD" value="1" literal="ADD"/>
    <eLiterals name="DELETE" value="2" literal="DELETE"/>
    <eLiterals name="MODIFY" value="3" literal="MODIFY"/>
    <eLiterals name="NIL" literal="NIL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Author">
    <eLiterals name="LEFT" value="1" literal="LEFT"/>
    <eLiterals name="RIGHT" value="2" literal="RIGHT"/>
    <eLiterals name="BOTH" value="3" literal="BOTH"/>
    <eLiterals name="NIL" literal="NIL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConflictKind">
    <eLiterals name="EQUIVALENT" value="1" literal="EQUIVALENT"/>
    <eLiterals name="CONTRADICTING" value="2" literal="CONTRADICTING"/>
    <eLiterals name="NIL" literal="NIL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SemanticDiff" eSuperTypes="#//SemanticObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" unique="false"
        lowerBound="1" eType="#//Author" defaultValueLiteral="NIL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SemanticConflict" eSuperTypes="#//SemanticObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="semanticdiffs" upperBound="-1"
        eType="#//SemanticDiff"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffPacman">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_initialPosition" unique="false"
        upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialPositionChangeStatus"
        unique="false" lowerBound="1" eType="#//ConflictKind" defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" upperBound="2"
        eType="#//DiffKind" defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" eType="#//ConflictKind"
        defaultValueLiteral="NIL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffGame" eSuperTypes="#//Game">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_score" upperBound="2"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scoreChangeStatus" unique="false"
        lowerBound="1" eType="#//ConflictKind" defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_lives" upperBound="2"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="livesChangeStatus" unique="false"
        lowerBound="1" eType="#//ConflictKind" defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" upperBound="2"
        eType="#//DiffKind" defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" eType="#//ConflictKind"
        defaultValueLiteral="NIL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffGame_entities"/>
  <eClassifiers xsi:type="ecore:EClass" name="DiffPositionableEntity_on">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//GridNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetCA" eType="#//GridNode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diffKind" eType="#//DiffKind"
        defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conflictKind" eType="#//ConflictKind"
        defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ConflictGroup" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffEnergizer" eSuperTypes="#//Energizer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_value" unique="false"
        upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueConflictKind" unique="false"
        lowerBound="1" eType="#//ConflictKind" defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="new_durations" upperBound="2"
        eType="#//EIntList" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="durationsConflictKind"
        unique="false" lowerBound="1" eType="#//ConflictKind" defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diffKind" upperBound="2"
        eType="#//DiffKind" defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conflictKind" eType="#//ConflictKind"
        defaultValueLiteral="NIL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SemanticObject" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_Game" upperBound="-1"
        eType="#//Game"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_GridNode"
        upperBound="-1" eType="#//GridNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_PositionableEntity"
        upperBound="-1" eType="#//PositionableEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffPositionableEntity_on"
        upperBound="-1" eType="#//DiffPositionableEntity_on"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PositionableEntity" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="on" lowerBound="1" eType="#//GridNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffon" upperBound="2"
        eType="#//DiffPositionableEntity_on"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffGridNode" eSuperTypes="#//GridNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diffKind" upperBound="2"
        eType="#//DiffKind" defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conflictKind" eType="#//ConflictKind"
        defaultValueLiteral="NIL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffFood" eSuperTypes="#//Food">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_value" upperBound="2"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueConflictKind" lowerBound="1"
        eType="#//ConflictKind" defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diffKind" upperBound="2"
        eType="#//DiffKind" defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conflictKind" eType="#//ConflictKind"
        defaultValueLiteral="NIL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EIntList">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NewEClass17"/>
</ecore:EPackage>
