package ca.umontreal.geodes.dsmcompare.dsmcHenshin;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

import org.eclipse.emf.ecore.EcorePackage;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.impl.ResourceSetImpl;
import org.eclipse.emf.ecore.xmi.impl.EcoreResourceFactoryImpl;
import org.eclipse.emf.ecore.xmi.impl.XMIResourceFactoryImpl;
import org.eclipse.emf.henshin.model.Module;
import org.eclipse.emf.henshin.model.Rule;
import org.eclipse.emf.henshin.model.Unit;
import org.eclipse.emf.henshin.model.resource.HenshinResourceSet;
import org.eclipse.emf.henshin.multicda.cda.ConflictAnalysis;
import org.eclipse.emf.henshin.multicda.cda.DependencyAnalysis;
import org.eclipse.emf.henshin.multicda.cda.MultiGranularAnalysis;
import org.eclipse.emf.henshin.multicda.cda.units.Atom;
import org.eclipse.emf.henshin.multicda.cda.units.Reason;
import org.eclipse.emf.henshin.multicda.cda.units.Span;
import org.eclipse.emf.henshin.preprocessing.Granularity;
import org.eclipse.emf.henshin.preprocessing.HenshinRuleLoader;
import org.eclipse.emf.henshin.preprocessing.NonDeletingPreparator;
import org.eclipse.emf.henshin.preprocessing.RulePair;
import org.eclipse.emf.henshin.preprocessing.RulePreparator;

public class MultiCdaSolver {	
	//Use it for finding the conflict between all SDRules and fine rules and (find conflicts among only unique SDRules)
	public String fullRulesSubDirectoryPath="";	
	public String cpaSemanticDiffModuleName="";	
	public String cpaAutoFineDiffRulesModuleName = "";
	public boolean  doRemoveAlternativeRules = false;//true for ordering of the SDRules
	public boolean doRemoveAutoGeneratedFineRules = false;////true for ordering of the SDRules
	public String domainName="";
	public ArrayList<Rule> rules;
	public int[][] conflictBinaryMatrix;
	public int[][] conflictCoarseMatrix;
	public int[][] conflictFineMatrix;
	public int[][] conflictAtomsMatrix;
	public int[][] dependencyMatrix;
	
	
	public static List<Granularity> granularities =  Arrays.asList(
			Granularity.binary,
			Granularity.coarse,
			Granularity.fine, 
			Granularity.atoms
			);
	
	String logTimeStamp = new SimpleDateFormat("yyyy-MM-dd_HH-mm-ss").format(new Date());
	String path= domainName + "\\"+logTimeStamp+ ".log" ;
	private ResourceSetImpl resourceSet;

	public boolean WRITE_LOGS = false;

	public static void main(String[] args) {
		new MultiCdaSolver().run(granularities);
	}
	
	public void execute() {
		run(granularities);
	}
	
	public void execute(List<Granularity> granularities, boolean doConflictAnalysis, boolean doDependencyAnalysis) {
		init();		
		//rules =  getRules(fullRulesSubDirectoryPath);
		prepareRules(rules);
		List<RulePair> nonDeleting = NonDeletingPreparator.prepareNonDeletingVersions(rules);
		if(doConflictAnalysis)
			doMultiGranularCdaConflictAnalysis(granularities, rules, nonDeleting);
		if(doDependencyAnalysis)
			doMultiGranularCdaDependencyAnalysis(granularities, rules, nonDeleting);
	}
	
	public void run(List<Granularity> granularities) {
		init();		
		//rules =  getRules(fullRulesSubDirectoryPath);
		prepareRules(rules);
		List<RulePair> nonDeleting = NonDeletingPreparator.prepareNonDeletingVersions(rules);
		doMultiGranularCdaConflictAnalysis(granularities, rules, nonDeleting);
		doMultiGranularCdaDependencyAnalysis(granularities, rules, nonDeleting);
	}
	
	public void removeAlternativeRules() {
		ArrayList<Rule> alternativeRules = new ArrayList<Rule>();
		for(Rule r:rules) {
			if(r.getName().matches(".*\\d.*") ||  r.getName().matches(".*_left.*") ||  r.getName().matches(".*_right.*")) {
				alternativeRules.add(r);
			}
		}
		rules.removeAll(alternativeRules);
	}
	

	public void init() {
		EcorePackage.eINSTANCE.eClass();

		Resource.Factory.Registry reg = Resource.Factory.Registry.INSTANCE;
		Map<String, Object> m = reg.getExtensionToFactoryMap();
		m.put("xmi", new XMIResourceFactoryImpl());
		resourceSet = new ResourceSetImpl();
		resourceSet.getResourceFactoryRegistry().getExtensionToFactoryMap().put("ecore",
				new EcoreResourceFactoryImpl());
		if (WRITE_LOGS )
			initLogs();
		rules =  getRules(fullRulesSubDirectoryPath, cpaSemanticDiffModuleName, cpaAutoFineDiffRulesModuleName);
		if(doRemoveAlternativeRules) {
			removeAlternativeRules();
		}
	}
	/*
	public List<Rule> getRules() {
		final File f = new File(MultiCdaSolver.class.getProtectionDomain().getCodeSource().getLocation().getPath());
		String filePath = f.toString();
		String projectPath = filePath.replaceAll("bin", "");
		String subDirectoryPath = "src\\org\\eclipse\\emf\\henshin\\examples\\cda";
		String fullSubDirectoryPath = projectPath + subDirectoryPath;
		File dir = new File(fullSubDirectoryPath);
		return HenshinRuleLoader.loadAllRulesFromFileSystemPaths(dir);
	}
	*/
	public ArrayList<Rule> getRules(String fullRulesSubDirectoryPath, String cpaSemanticDiffModuleName, String cpaAutoFineDiffRulesModuleName) {
		//cpaAutoFineRulesModule 	= henshinRuleResourceSet.getModule(cpaAutoFineDiffRulesModuleName);
		//cpaSemanticRuleModule 	= henshinRuleResourceSet.getModule(cpaSemanticDiffModuleName);
		//String cpaRulePath = fullRulesSubDirectoryPath + cpaSemanticDiffModuleName;
		//String autoRulePath = fullRulesSubDirectoryPath + cpaAutoFineDiffRulesModuleName;	


		Module cpaSemanticRuleModule 	= null;
		Module cpaAutoFineRulesModule 	= null;
		HenshinResourceSet henshinRuleResourceSet=null;
		henshinRuleResourceSet = new HenshinResourceSet(fullRulesSubDirectoryPath);
		cpaSemanticRuleModule 	= henshinRuleResourceSet.getModule(cpaSemanticDiffModuleName);			
		List<Unit> usCPA = cpaSemanticRuleModule.getUnits().stream().filter(f->f.getClass().toString().contains("Rule")).collect(Collectors.toList());
		
		//List<Rule> rulesSemanticCPA     =   CPAUtility.extractAllRules(cpaSemanticRuleModule);
		//List<Rule> attributeChangeFineRules 		= CPAUtility.extractAllRules(cpaAutoFineRulesModule);
		
		//ArrayList<Rule> rulesSemanticCPA = new ArrayList<Rule>();
		//ArrayList<Rule> rulesAutoFineRules = new ArrayList<Rule>();
		ArrayList<Rule> ruleList = new ArrayList<Rule>();
		for(Unit u:usCPA) {
			ruleList.add((Rule) u);
		}
		
		if(doRemoveAutoGeneratedFineRules == false) {
			cpaAutoFineRulesModule 	= henshinRuleResourceSet.getModule(cpaAutoFineDiffRulesModuleName);
			List<Unit> usFines = cpaAutoFineRulesModule.getUnits().stream().filter(f->f.getClass().toString().contains("Rule")).collect(Collectors.toList());
			for(Unit u:usFines) {
				ruleList.add((Rule) u);
			}
		}
		
		//File dir = new File(fullRulesSubDirectoryPath);
		//ArrayList<Rule> ruleList = new ArrayList();
		//ruleList.addAll(HenshinRuleLoader.loadAllRulesFromFileSystemPaths(dir));
		return ruleList;
	}
	
	protected void doMultiGranularCdaConflictAnalysis(List<Granularity> granularities,  List<Rule> rules,
			List<RulePair> nonDeleting) {
		logbn("Starting CDA with " + rules.size() + " rules CONFLICT Analysis.");

		if (granularities.contains(Granularity.atoms)) {
			logn("[MultiCDA] Computing conflict atoms-computeAtoms:");
			for (Rule r1 : rules) {
				for (RulePair r2 : nonDeleting) {
					long time = System.currentTimeMillis();
					MultiGranularAnalysis ca = 
							 new ConflictAnalysis(r1, r2.getCopy());
					Set<? extends Atom> result = ca.computeAtoms();
					log(result.size() + " ");
					tlog(System.currentTimeMillis() - time + " ");
				}
				logbn("   | " + r1.getName());
			}
			logbn("");
		}

		if (granularities.contains(Granularity.binary)) {
			conflictBinaryMatrix = new int[rules.size()][rules.size()];
			int i=-1,j;
			logn("[MultiCDA] Computing  Granularity.binary-conflict Results:");
			for (Rule r1 : rules) {
				String exMsg="";
				++i;
				j=-1;
				for (RulePair r2 : nonDeleting) {
					++j;
					long time = System.currentTimeMillis();
					MultiGranularAnalysis ca = 
							 new ConflictAnalysis(r1, r2.getCopy());
					try {
						Span result = ca.computeResultsBinary();						
						log(result == null ? "0 " : "1 ");
						conflictBinaryMatrix[i][j]= result == null ? 0  : 1;
						tlog(System.currentTimeMillis() - time + " ");
					}
					catch(Exception ex) {
						log("0 ");//e:Exception
						exMsg += "["+r2.getCopy().getName()+"]";
						conflictBinaryMatrix[i][j]= -1;
						tlog(System.currentTimeMillis() - time + " ");
					}
					
				}
				log("   | " + r1.getName());
				logbn("   |Exceptions: " + exMsg);
			}
			logbn("");
		}

		if (granularities.contains(Granularity.coarse)) {
			conflictCoarseMatrix = new int[rules.size()][rules.size()];
			int i=-1,j;
			logn("[MultiCDA] Computing minimal(Granularity.coarse) conflict Results:");
			for (Rule r1 : rules) {
				++i;
				j=-1;
				for (RulePair r2 : nonDeleting) {
					++j;
					long time = System.currentTimeMillis();
					MultiGranularAnalysis ca = 
							 new ConflictAnalysis(r1, r2.getCopy());
					try {
						Set<? extends Reason> result = ca.computeResultsCoarse();
						log(result.size() + " ");
						conflictCoarseMatrix[i][j]= result == null ? 0  : result.size();
					}
					catch(Exception ex) {
						log("0" + " ");
						conflictCoarseMatrix[i][j]= -1;
					}
					tlog(System.currentTimeMillis() - time + " ");
				}
				logbn("   | " + r1.getName());
			}
			logbn("");
		}

		if (granularities.contains(Granularity.fine)) {
			conflictFineMatrix = new int[rules.size()][rules.size()];
			int i=-1,j;
			logn("[MultiCDA] Computing Granularity.fine conflict Results:");
			for (Rule r1 : rules) {
				++i;
				j=-1;
				List<Integer> resultRow = new ArrayList<Integer>();
				for (RulePair r2 : nonDeleting) {
					++j;
					long time = System.currentTimeMillis();
					MultiGranularAnalysis ca = 
							 new ConflictAnalysis(r1, r2.getCopy());
					try{
						Set<? extends Reason> result = ca.computeResultsFine();
						log(result.size() + ", ");
						conflictFineMatrix[i][j]= result == null ? 0  : result.size();
					
						tlog(System.currentTimeMillis() - time + " ");
						resultRow.add(result.size());
					}
					catch(Exception ex) {
						log("0" + ", ");
						conflictFineMatrix[i][j]= -1;
						resultRow.add(0);
					}
				}
				logbn("   | " + r1.getName());
			}
			logbn("");
		}
		
		if (granularities.contains(Granularity.atoms)) {
			conflictAtomsMatrix = new int[rules.size()][rules.size()];
			int i=-1,j;
			logn("[MultiCDA] Computing Granularity.atoms conflict Results:");
			for (Rule r1 : rules) {
				++i;
				j=-1;
				List<Integer> resultRow = new ArrayList<Integer>();
				for (RulePair r2 : nonDeleting) {
					++j;
					long time = System.currentTimeMillis();
					MultiGranularAnalysis ca = 
							 new ConflictAnalysis(r1, r2.getCopy());
					try{
						Set<? extends Atom> result =  ca.computeAtoms();// ca.computeResultsFine();
						log(result.size() + ", ");
						conflictAtomsMatrix[i][j]= result == null ? 0  : result.size();
					
						tlog(System.currentTimeMillis() - time + " ");
						resultRow.add(result.size());
					}
					catch(Exception ex) {
						log("0" + ", ");
						conflictAtomsMatrix[i][j]= -1;
						resultRow.add(0);
					}
				}
				logbn("   | " + r1.getName());
			}
			logbn("");
		}
	}

	
	
	protected void doMultiGranularCdaDependencyAnalysis(List<Granularity> granularities,  List<Rule> rules,
			List<RulePair> nonDeleting) {
		logbn("Starting CDA with " + rules.size() + " rules for DEPENDENCY Analysis.");

		if (granularities.contains(Granularity.atoms)) {
			logn("[MultiCDA] Computing DEPENDENCY atoms:");
			for (Rule r1 : rules) {
				for (RulePair r2 : nonDeleting) {
					long time = System.currentTimeMillis();
					MultiGranularAnalysis ca = 
							 new DependencyAnalysis(r1, r2.getCopy());
					Set<? extends Atom> result = ca.computeAtoms();
					log(result.size() + " ");
					tlog(System.currentTimeMillis() - time + " ");
				}
				logbn("   | " + r1.getName());
			}
			logbn("");
		}

		if (granularities.contains(Granularity.binary)) {
			dependencyMatrix = new int[rules.size()][rules.size()];
			int i=-1,j;
			logn("[MultiCDA] Computing DEPENDENCY binary granularity:");
			for (Rule r1 : rules) {
				++i;
				j=-1;
				for (RulePair r2 : nonDeleting) {
					++j;
					long time = System.currentTimeMillis();
					MultiGranularAnalysis ca = 
							 new DependencyAnalysis(r1, r2.getCopy());
					Span result = ca.computeResultsBinary();
					log(result == null ? "0 " : "1 ");
					dependencyMatrix[i][j]=result == null ? 0 : 1;
					tlog(System.currentTimeMillis() - time + " ");
				}
				logbn("   | " + r1.getName());
			}
			logbn("");
		}

		if (granularities.contains(Granularity.coarse)) {
			logn("[MultiCDA] Computing minimal DEPENDENCY reasons:");
			for (Rule r1 : rules) {
				for (RulePair r2 : nonDeleting) {
					long time = System.currentTimeMillis();
					MultiGranularAnalysis ca = 
							 new DependencyAnalysis(r1, r2.getCopy());
					Set<? extends Reason> result = ca.computeResultsCoarse();
					log(result.size() + " ");
					tlog(System.currentTimeMillis() - time + " ");
				}
				logbn("   | " + r1.getName());
			}
			logbn("");
		}

		if (granularities.contains(Granularity.fine)) {
			logn("[MultiCDA] Computing fINE DEPENDENCY reasons:");
			for (Rule r1 : rules) {
				List<Integer> resultRow = new ArrayList<Integer>();
				for (RulePair r2 : nonDeleting) {
					long time = System.currentTimeMillis();
					MultiGranularAnalysis ca = 
							 new DependencyAnalysis(r1, r2.getCopy());
					Set<? extends Reason> result = ca.computeResultsFine();
					log(result.size() + " ");
					tlog(System.currentTimeMillis() - time + " ");
					resultRow.add(result.size());
				}
				logbn("   | " + r1.getName());
			}
			logbn("");
		}
	}

	protected void initLogs() {
		try {
			Files.write(Paths.get( "logs\\time\\"+path), new String().getBytes(), StandardOpenOption.CREATE_NEW);
			Files.write(Paths.get( "logs\\results\\"+path), new String().getBytes(), StandardOpenOption.CREATE_NEW);
		} catch (IOException e) {
			e.printStackTrace();
		}
	}

	protected void logbn(String string) {
		log(string+"\n");
		tlog(string+"\n");
	}

	protected void tlog(String string) {
		if (WRITE_LOGS) {
			try {
				Files.write(Paths.get( "logs\\time\\"+path), string.getBytes(), StandardOpenOption.APPEND);
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
	}
	
	protected void log(String string) {
		System.out.print(string);
		

		if (WRITE_LOGS) {
		try {
			Files.write(Paths.get( "logs\\results\\"+path), string.getBytes(), StandardOpenOption.APPEND);
		} catch (IOException e) {
			e.printStackTrace();
		}
		}
	}

	protected void logn(String string) {
		log(string+ "\n");
	}



	private static void prepareRules(List<Rule> rules) {
		List<Rule> prepared = new ArrayList<Rule>();
		rules.removeAll(rules.stream().filter(r -> !r.getMultiRules().isEmpty()).collect(Collectors.toList()));
		rules.forEach(r -> prepared.add(RulePreparator.prepareRule(r)));
		rules.clear();
		rules.addAll(prepared);
	}
}
