<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="moveCaseDSDiffMM" nsURI="www.moveCaseDSDiffMM.org" nsPrefix="moveCaseDSDiffMM">
  <eClassifiers xsi:type="ecore:EClass" name="A">
    <eStructuralFeatures xsi:type="ecore:EReference" name="m" upperBound="-1" eType="#//B"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffm" upperBound="-1"
        eType="#//DiffA_m" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B">
    <eStructuralFeatures xsi:type="ecore:EReference" name="p" upperBound="-1" eType="#//B"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffp" lowerBound="1" eType="#//DiffB_p"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffA" eSuperTypes="#//A">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" upperBound="2"
        eType="#//DiffKind" defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conflictKind" eType="#//ConflictKind"
        defaultValueLiteral="NIL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffB" eSuperTypes="#//B">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" upperBound="2"
        eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conflictKind" eType="#//ConflictKind"
        defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_x" upperBound="2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffA_m">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//B"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" upperBound="3"
        eType="#//DiffKind" defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conflictKind" eType="#//ConflictKind"
        defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetCA" eType="#//B"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffB_p">
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//B"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diffKind" upperBound="3"
        eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conflictKind" eType="#//ConflictKind"
        defaultValueLiteral="NIL"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetCA" eType="#//B"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AUTHOR">
    <eLiterals name="LEFT" literal="LEFT"/>
    <eLiterals name="RIGHT" value="1" literal="RIGHT"/>
    <eLiterals name="EQUAL" value="2" literal="EQUAL"/>
    <eLiterals name="NIL" value="4" literal="NIL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConflictKind">
    <eLiterals name="EQUIVALENT" literal="EQUIVALENT"/>
    <eLiterals name="CONTRADICTING" value="1" literal="CONTRADICTING"/>
    <eLiterals name="NIL" value="2" literal="NIL"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DiffKind">
    <eLiterals name="ADD" literal="ADD"/>
    <eLiterals name="DELETE" value="1" literal="DELETE"/>
    <eLiterals name="MODIFY" value="2" literal="MODIFY"/>
    <eLiterals name="NIL" value="3" literal="NIL"/>
  </eClassifiers>
</ecore:EPackage>
