#

pluginName = RDB Editor Editor
providerName = www.example.org

_UI_PacmanEditor_menu = &Pacman Editor

_UI_CreateChild_menu_item = &New Child
_UI_CreateSibling_menu_item = N&ew Sibling

_UI_ShowPropertiesView_menu_item = Show &Properties View
_UI_RefreshViewer_menu_item = &Refresh

_UI_SelectionPage_label = Selection
_UI_ParentPage_label = Parent
_UI_ListPage_label = List
_UI_TreePage_label = Tree
_UI_TablePage_label = Table
_UI_TreeWithColumnsPage_label = Tree with Columns
_UI_ObjectColumn_label = Object
_UI_SelfColumn_label = Self

_UI_NoObjectSelected = Selected Nothing
_UI_SingleObjectSelected = Selected Object: {0}
_UI_MultiObjectSelected = Selected {0} Objects

_UI_OpenEditorError_label = Open Editor

_UI_Wizard_category = Example EMF Model Creation Wizards

_UI_CreateModelError_message = Problems encountered in file "{0}"

_UI_PacmanModelWizard_label = Pacman Model
_UI_PacmanModelWizard_description = Create a new Pacman model

_UI_PacmanEditor_label = Pacman Model Editor

_UI_PacmanEditorFilenameDefaultBase = My
_UI_PacmanEditorFilenameExtensions = pacman

_UI_Wizard_label = New

_WARN_FilenameExtension = The file name must end in ''.{0}''
_WARN_FilenameExtensions = The file name must have one of the following extensions: {0}

_UI_ModelObject = &Model Object
_UI_XMLEncoding = &XML Encoding
_UI_XMLEncodingChoices = UTF-8 ASCII UTF-16 UTF-16BE UTF-16LE ISO-8859-1
_UI_Wizard_initial_object_description = Select a model object to create

_UI_FileConflict_label = File Conflict
_WARN_FileConflict = There are unsaved changes that conflict with changes made outside the editor.  Do you wish to discard this editor's changes?

_UI_PacmanDiffMMEditor_menu = &PacmanDiffMM Editor
_UI_PacmanDiffMMModelWizard_label = PacmanDiffMM Model
_UI_PacmanDiffMMModelWizard_description = Create a new PacmanDiffMM model
_UI_PacmanDiffMMEditor_label = PacmanDiffMM Model Editor
_UI_PacmanDiffMMEditorFilenameDefaultBase = My
_UI_PacmanDiffMMEditorFilenameExtensions = pacmandiffmm

_UI_RefactoringEditor_menu = &Refactoring Editor
_UI_RefactoringModelWizard_label = Refactoring Model
_UI_RefactoringModelWizard_description = Create a new Refactoring model
_UI_RefactoringEditor_label = Refactoring Model Editor
_UI_RefactoringEditorFilenameDefaultBase = My
_UI_RefactoringEditorFilenameExtensions = refactoring

_UI_RefactoringDiffMMEditor_menu = &RefactoringDiffMM Editor
_UI_RefactoringDiffMMModelWizard_label = RefactoringDiffMM Model
_UI_RefactoringDiffMMModelWizard_description = Create a new RefactoringDiffMM model
_UI_RefactoringDiffMMEditor_label = RefactoringDiffMM Model Editor
_UI_RefactoringDiffMMEditorFilenameDefaultBase = My
_UI_RefactoringDiffMMEditorFilenameExtensions = refactoringdiffmm

