<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="arduinoDiffMM" nsURI="http://www.obeo.fr/arduinoDiffMM" nsPrefix="arduinoDiffMM">
  <eClassifiers xsi:type="ecore:EClass" name="Hardware" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="platforms" lowerBound="1"
        upperBound="-1" eType="#//Platform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
        eType="#//Module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectors" upperBound="-1"
        eType="#//Connector" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffplatforms" upperBound="-1"
        eType="#//DiffHardware_platforms" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffmodules" upperBound="-1"
        eType="#//DiffHardware_modules" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffconnectors" upperBound="-1"
        eType="#//DiffHardware_connectors" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Platform" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digitalPins" upperBound="-1"
        eType="#//DigitalPin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="analogPins" upperBound="-1"
        eType="#//AnalogPin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffdigitalPins" upperBound="-1"
        eType="#//DiffPlatform_digitalPins" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffanalogPins" upperBound="-1"
        eType="#//DiffPlatform_analogPins" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module" abstract="true" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ModuleKind"
        defaultValueLiteral="digital"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="image" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="library" eType="#//Library"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigitalPin" eSuperTypes="#//Pin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Pin" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnalogPin" eSuperTypes="#//Pin"/>
  <eClassifiers xsi:type="ecore:EClass" name="Sketch" eSuperTypes="#//NamedElement #//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hardware" lowerBound="1"
        eType="#//Hardware"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
        eType="#//Instruction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="functions" upperBound="-1"
        eType="#//Function" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffhardware" upperBound="2"
        eType="#//DiffSketch_hardware" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffinstructions" upperBound="-1"
        eType="#//DiffSketch_instructions" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="difffunctions" upperBound="-1"
        eType="#//DiffSketch_functions" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Project">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hardware" eType="#//Hardware"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sketch" eType="#//Sketch"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modules" upperBound="-1"
        eType="#//Module" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="platform" upperBound="-1"
        eType="#//Platform" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainspecificdiffs" upperBound="-1"
        eType="#//DomainSpecificDiff" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffhardware" upperBound="2"
        eType="#//DiffProject_hardware" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffsketch" upperBound="2"
        eType="#//DiffProject_sketch" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffmodules" upperBound="-1"
        eType="#//DiffProject_modules" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffplatform" upperBound="-1"
        eType="#//DiffProject_platform" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffdomainspecificdiffs"
        upperBound="-1" eType="#//DiffProject_domainspecificdiffs" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instruction" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="previous" eType="#//Instruction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="next" eType="#//Instruction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffprevious" upperBound="2"
        eType="#//DiffInstruction_previous" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffnext" upperBound="2"
        eType="#//DiffInstruction_next" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Status" eSuperTypes="#//ModuleInstruction #//Value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sensor" eType="#//Sensor"
        eOpposite="#//Sensor/status"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffsensor" upperBound="2"
        eType="#//DiffStatus_sensor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Level" eSuperTypes="#//ModuleInstruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="level" lowerBound="1" eType="#//Value"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="difflevel" upperBound="2"
        eType="#//DiffLevel_level" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleInstruction" abstract="true" eSuperTypes="#//Instruction #//Parameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" lowerBound="1"
        eType="#//Module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffmodule" upperBound="2"
        eType="#//DiffModuleInstruction_module" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Control" abstract="true" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
        eType="#//Instruction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffinstructions" upperBound="-1"
        eType="#//DiffControl_instructions" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Utilities" abstract="true" eSuperTypes="#//Instruction #//Parameter"/>
  <eClassifiers xsi:type="ecore:EClass" name="IO" abstract="true" eSuperTypes="#//Instruction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Delay" eSuperTypes="#//Utilities">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" eType="#//Time"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Time">
    <eLiterals name="MilliSecond"/>
    <eLiterals name="MicroSecond"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputModule" eSuperTypes="#//Module"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutputModule" eSuperTypes="#//Module"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ModuleKind">
    <eLiterals name="digital"/>
    <eLiterals name="analog"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connector">
    <eStructuralFeatures xsi:type="ecore:EReference" name="pin" eType="#//Pin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="module" eType="#//Module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffpin" upperBound="2"
        eType="#//DiffConnector_pin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffmodule" upperBound="2"
        eType="#//DiffConnector_module" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repeat" eSuperTypes="#//Control">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iteration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sensor" eSuperTypes="#//ModuleInstruction #//BooleanOperator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="status" upperBound="-1"
        eType="#//Status" eOpposite="#//Status/sensor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffstatus" upperBound="-1"
        eType="#//DiffSensor_status" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="While" eSuperTypes="#//Control">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//BooleanOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffcondition" upperBound="2"
        eType="#//DiffWhile_condition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MathOperator" abstract="true" eSuperTypes="#//Value #//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" lowerBound="1" eType="#//Value"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Value"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//OperatorKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffleft" upperBound="2"
        eType="#//DiffMathOperator_left" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffright" upperBound="2"
        eType="#//DiffMathOperator_right" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OperatorKind">
    <eLiterals name="equal"/>
    <eLiterals name="minus"/>
    <eLiterals name="upper"/>
    <eLiterals name="lower"/>
    <eLiterals name="plus"/>
    <eLiterals name="diff"/>
    <eLiterals name="upperOrEqual"/>
    <eLiterals name="lowerOrEqual"/>
    <eLiterals name="mul"/>
    <eLiterals name="div"/>
    <eLiterals name="min"/>
    <eLiterals name="max"/>
    <eLiterals name="pourcent"/>
    <eLiterals name="and"/>
    <eLiterals name="or"/>
    <eLiterals name="not"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//Value #//Instruction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Set" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variable" lowerBound="1"
        eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Value"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffvariable" upperBound="2"
        eType="#//DiffSet_variable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffvalue" upperBound="2"
        eType="#//DiffSet_value" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumericalOperator" eSuperTypes="#//MathOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanOperator" eSuperTypes="#//MathOperator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Value" abstract="true" eSuperTypes="#//Instruction #//Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="#//Value"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Library">
    <eLiterals name="none"/>
    <eLiterals name="servo"/>
    <eLiterals name="music"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="If" eSuperTypes="#//Control">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" lowerBound="1"
        eType="#//BooleanOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffcondition" upperBound="2"
        eType="#//DiffIf_condition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paramDefs" upperBound="-1"
        eType="#//ParameterDefinition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="instructions" upperBound="-1"
        eType="#//Instruction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffparamDefs" upperBound="-1"
        eType="#//DiffFunction_paramDefs" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffinstructions" upperBound="-1"
        eType="#//DiffFunction_instructions" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ParameterType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" eType="#//ParameterDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffdefinition" upperBound="2"
        eType="#//DiffParameter_definition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionCall" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" lowerBound="1"
        eType="#//Function"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffdefinition" upperBound="2"
        eType="#//DiffFunctionCall_definition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffparameters" upperBound="-1"
        eType="#//DiffFunctionCall_parameters" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterType">
    <eLiterals name="Delay"/>
    <eLiterals name="Level"/>
    <eLiterals name="Status"/>
    <eLiterals name="Constant"/>
    <eLiterals name="Sensor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterCall" eSuperTypes="#//Instruction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="definition" eType="#//ParameterDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffdefinition" upperBound="2"
        eType="#//DiffParameterCall_definition" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ClassOp">
    <eLiterals name="ADD" literal="ADD"/>
    <eLiterals name="DELETE" value="1" literal="DELETE"/>
    <eLiterals name="MODIFY" value="2" literal="MODIFY"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AscOp">
    <eLiterals name="ADD" literal="ADD"/>
    <eLiterals name="DELETE" value="1" literal="DELETE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainSpecificDiff">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_Hardware"
        upperBound="-1" eType="#//Hardware"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_Platform"
        upperBound="-1" eType="#//Platform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_Module"
        upperBound="-1" eType="#//Module"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_DigitalPin"
        upperBound="-1" eType="#//DigitalPin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_Pin"
        upperBound="-1" eType="#//Pin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_AnalogPin"
        upperBound="-1" eType="#//AnalogPin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_Sketch"
        upperBound="-1" eType="#//Sketch"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_Instruction"
        upperBound="-1" eType="#//Instruction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_Status"
        upperBound="-1" eType="#//Status"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_Level"
        upperBound="-1" eType="#//Level"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_ModuleInstruction"
        upperBound="-1" eType="#//ModuleInstruction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_Control"
        upperBound="-1" eType="#//Control"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_Utilities"
        upperBound="-1" eType="#//Utilities"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_IO"
        upperBound="-1" eType="#//IO"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_Delay"
        upperBound="-1" eType="#//Delay"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_InputModule"
        upperBound="-1" eType="#//InputModule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_OutputModule"
        upperBound="-1" eType="#//OutputModule"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_NamedElement"
        upperBound="-1" eType="#//NamedElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_Connector"
        upperBound="-1" eType="#//Connector"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_Repeat"
        upperBound="-1" eType="#//Repeat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_Sensor"
        upperBound="-1" eType="#//Sensor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_While"
        upperBound="-1" eType="#//While"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_MathOperator"
        upperBound="-1" eType="#//MathOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_Variable"
        upperBound="-1" eType="#//Variable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_Set"
        upperBound="-1" eType="#//Set"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_NumericalOperator"
        upperBound="-1" eType="#//NumericalOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_BooleanOperator"
        upperBound="-1" eType="#//BooleanOperator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_Value"
        upperBound="-1" eType="#//Value"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_Constant"
        upperBound="-1" eType="#//Constant"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_If"
        upperBound="-1" eType="#//If"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_Function"
        upperBound="-1" eType="#//Function"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_ParameterDefinition"
        upperBound="-1" eType="#//ParameterDefinition"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_Parameter"
        upperBound="-1" eType="#//Parameter"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_FunctionCall"
        upperBound="-1" eType="#//FunctionCall"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DomainSpecificDiff_ParameterCall"
        upperBound="-1" eType="#//ParameterCall"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffHardware" eSuperTypes="#//Hardware">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffHardware_platforms">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Platform"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffHardware_modules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Module"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffHardware_connectors">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Connector"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffPlatform" eSuperTypes="#//Platform">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_image" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffPlatform_digitalPins">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//DigitalPin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffPlatform_analogPins">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//AnalogPin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffDigitalPin" eSuperTypes="#//DigitalPin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffAnalogPin" eSuperTypes="#//AnalogPin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffSketch" eSuperTypes="#//Sketch">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffSketch_hardware">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Hardware"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffSketch_instructions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Instruction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffSketch_functions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Function"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffProject" eSuperTypes="#//Project">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffProject_hardware">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Hardware"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffProject_sketch">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Sketch"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffProject_modules">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Module"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffProject_platform">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Platform"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffProject_domainspecificdiffs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//DomainSpecificDiff"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffInstruction_previous">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Instruction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffInstruction_next">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Instruction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffStatus" eSuperTypes="#//Status">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffStatus_sensor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Sensor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffLevel" eSuperTypes="#//Level">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffLevel_level">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffModuleInstruction_module">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Module"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffControl_instructions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Instruction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffDelay" eSuperTypes="#//Delay">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_unit" eType="#//Time"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffInputModule" eSuperTypes="#//InputModule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_kind" eType="#//ModuleKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_image" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_library" eType="#//Library"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffOutputModule" eSuperTypes="#//OutputModule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_kind" eType="#//ModuleKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_image" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_library" eType="#//Library"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffConnector" eSuperTypes="#//Connector">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffConnector_pin">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Pin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffConnector_module">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Module"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffRepeat" eSuperTypes="#//Repeat">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_iteration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffSensor" eSuperTypes="#//Sensor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_operator" eType="#//OperatorKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffSensor_status">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Status"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffWhile" eSuperTypes="#//While">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffWhile_condition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//BooleanOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffMathOperator_left">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffMathOperator_right">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffVariable" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffSet" eSuperTypes="#//Set">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffSet_variable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Variable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffSet_value">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Value"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffNumericalOperator" eSuperTypes="#//NumericalOperator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_operator" eType="#//OperatorKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffBooleanOperator" eSuperTypes="#//BooleanOperator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_operator" eType="#//OperatorKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffConstant" eSuperTypes="#//Constant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffIf" eSuperTypes="#//If">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffIf_condition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//BooleanOperator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffFunction" eSuperTypes="#//Function">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffFunction_paramDefs">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//ParameterDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffFunction_instructions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Instruction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffParameterDefinition" eSuperTypes="#//ParameterDefinition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_type" eType="#//ParameterType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffParameter_definition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//ParameterDefinition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffFunctionCall" eSuperTypes="#//FunctionCall">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffFunctionCall_definition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Function"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffFunctionCall_parameters">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Parameter"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffParameterCall" eSuperTypes="#//ParameterCall">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//ClassOp"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffParameterCall_definition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="#//AscOp"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//ParameterDefinition"/>
  </eClassifiers>
</ecore:EPackage>
