<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pacmanCRRuleMM" nsURI="http://www.zadahmad.org/dsmcompare/pacmanCRRuleMM"
    nsPrefix="pacmanCRRuleMM">
  <eClassifiers xsi:type="ecore:EEnum" name="AUTHOR">
    <eLiterals name="NON" literal="NON"/>
    <eLiterals name="LEFT" value="1" literal="LEFT"/>
    <eLiterals name="RIGHT" value="2" literal="RIGHT"/>
    <eLiterals name="EQUAL" value="3" literal="EQUAL"/>
    <eLiterals name="MIXED" value="4" literal="MIXED"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ChangeStatus">
    <eLiterals name="NON" literal="NON"/>
    <eLiterals name="EQUIVALENT" value="1" literal="EQUIVALENT"/>
    <eLiterals name="CONTRADICTING" value="2" literal="CONTRADICTING"/>
    <eLiterals name="MERGE_ADD" value="3" literal="MERGE_ADD"/>
    <eLiterals name="MERGE_DELETE" value="4" literal="MERGE_DELETE"/>
    <eLiterals name="MERGE_MODIFY" value="5" literal="MERGE_MODIFY"/>
    <eLiterals name="MERGE_DELETE_CREATE" value="6" literal="MERGE_DELETE_CREATE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConflictGranularity">
    <eLiterals name="NIL" literal="NIL"/>
    <eLiterals name="Semantic_Semantic" value="1" literal="Semantic_Semantic"/>
    <eLiterals name="Semantic_Fine" value="2" literal="Semantic_Fine"/>
    <eLiterals name="Fine_Fine" value="3" literal="Fine_Fine"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConflictResolutionStrategy">
    <eLiterals name="NIL" literal="NIL"/>
    <eLiterals name="Keep_Left" value="1" literal="Keep_Left"/>
    <eLiterals name="Keep_Right" value="2" literal="Keep_Right"/>
    <eLiterals name="Keep_Semantic_Difference" value="3" literal="Keep_Semantic_Difference"/>
    <eLiterals name="Apply_None" value="4" literal="Apply_None"/>
    <eLiterals name="Apply_Left_Then_Right" value="5" literal="Apply_Left_Then_Right"/>
    <eLiterals name="Apply_Right_Then_Left" value="6" literal="Apply_Right_Then_Left"/>
    <eLiterals name="Apply_A_User_Defined_Resolution_Pattern" value="7" literal="Apply_A_User_Defined_Resolution_Pattern"/>
    <eLiterals name="Custom_Change_At_Time_Of_Merge" value="8" literal="Custom_Change_At_Time_Of_Merge"/>
    <eLiterals name="Suggest_A_Resolution_Needing_Approval" value="9" literal="Suggest_A_Resolution_Needing_Approval"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConflictResolutionType">
    <eLiterals name="Pending" literal="Pending"/>
    <eLiterals name="Resolved" value="1" literal="Resolved"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DiffKind">
    <eLiterals name="NON" literal="NON"/>
    <eLiterals name="ADD" value="1" literal="ADD"/>
    <eLiterals name="DELETE" value="2" literal="DELETE"/>
    <eLiterals name="MODIFY" value="3" literal="MODIFY"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GhostStrategy">
    <eLiterals name="Blinky" literal="Blinky"/>
    <eLiterals name="Pinky" value="1" literal="Pinky"/>
    <eLiterals name="Inky" value="2"/>
    <eLiterals name="Clyde" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_ConflictResolution" eSuperTypes="#//Pattern_SemanticObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ResolutionType" unique="false"
        lowerBound="1" eType="#//ConflictResolutionType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ResolutionStrategy" unique="false"
        lowerBound="1" eType="#//ConflictResolutionStrategy"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semanticconflicts" ordered="false"
        upperBound="-1" eType="#//Pattern_SemanticConflict"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffEnergizer" eSuperTypes="#//Pattern_PositionableEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMerged" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_id_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_id_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_value_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_value_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="durationsChangeStatus"
        unique="false" lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="new_durations_Left" lowerBound="1"
        eType="#//Pattern__ListEInt" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="new_durations_Right" lowerBound="1"
        eType="#//Pattern__ListEInt" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffFood" eSuperTypes="#//Pattern_PositionableEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMerged" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_id_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_id_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_value_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_value_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffFruit" eSuperTypes="#//Pattern_PositionableEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMerged" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_id_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_id_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_value_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_value_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_location_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_location_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="locationChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffGame" eSuperTypes="#//Pattern_Game">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMerged" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_id_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_id_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_lives_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_lives_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="livesChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_score_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_score_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scoreChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffGame_entities">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMerged" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_Group" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Pattern_PositionableEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffGame_gridnodes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMerged" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_Group" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Pattern_GridNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffGhost" eSuperTypes="#//Pattern_PositionableEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMerged" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_id_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_id_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_strategy_Left" unique="false"
        lowerBound="1" eType="#//GhostStrategy"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_strategy_Right" unique="false"
        lowerBound="1" eType="#//GhostStrategy"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strategyChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffGridNode" eSuperTypes="#//Pattern_GridNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMerged" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_id_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_id_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffGridNode_down">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMerged" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_Group" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Pattern_GridNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffGridNode_left">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMerged" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_Group" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Pattern_GridNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffGridNode_right">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMerged" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_Group" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Pattern_GridNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffGridNode_up">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMerged" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_Group" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Pattern_GridNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffPacman" eSuperTypes="#//Pattern_PositionableEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMerged" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_id_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_id_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="idChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_initialPosition_Left"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_initialPosition_Right"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialPositionChangeStatus"
        unique="false" lowerBound="1" eType="#//ChangeStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffPositionableEntity_on">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//DiffKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMerged" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_Group" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Pattern_GridNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_Energizer" eSuperTypes="#//Pattern_PositionableEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="durations" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_Food" eSuperTypes="#//Pattern_PositionableEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_Fruit" eSuperTypes="#//Pattern_PositionableEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_Game">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lives" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gridnodes" upperBound="-1"
        eType="#//Pattern_GridNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Pattern_PositionableEntity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffgridnodes" upperBound="-1"
        eType="#//Pattern_DiffGame_gridnodes" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffentities" upperBound="-1"
        eType="#//Pattern_DiffGame_entities" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_Ghost" eSuperTypes="#//Pattern_PositionableEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strategy" lowerBound="1"
        eType="#//GhostStrategy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_GridNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="up" eType="#//Pattern_GridNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="down" eType="#//Pattern_GridNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//Pattern_GridNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//Pattern_GridNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffup" upperBound="-1"
        eType="#//Pattern_DiffGridNode_up" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffdown" upperBound="-1"
        eType="#//Pattern_DiffGridNode_down" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffleft" upperBound="-1"
        eType="#//Pattern_DiffGridNode_left" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffright" upperBound="-1"
        eType="#//Pattern_DiffGridNode_right" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_Pacman" eSuperTypes="#//Pattern_PositionableEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialPosition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_PositionableEntity" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="on" lowerBound="1" eType="#//Pattern_GridNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffon" upperBound="-1"
        eType="#//Pattern_DiffPositionableEntity_on" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_SemanticConflict" eSuperTypes="#//Pattern_SemanticObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conflict_kind" unique="false"
        lowerBound="1" eType="#//ChangeStatus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="conflict_Granularity" unique="false"
        lowerBound="1" eType="#//ConflictGranularity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="semanticdiffs" ordered="false"
        upperBound="-1" eType="#//Pattern_SemanticDiff"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_SemanticDiff" eSuperTypes="#//Pattern_SemanticObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" unique="false"
        lowerBound="1" eType="#//AUTHOR"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern_SemanticObject" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffEnergizer"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffEnergizer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffFood"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffFood"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffFruit"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffFruit"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffGame"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffGame"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffGame_entities"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffGame_entities"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffGame_gridnodes"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffGame_gridnodes"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffGhost"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffGhost"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffGridNode"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffGridNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffGridNode_down"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffGridNode_down"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffGridNode_left"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffGridNode_left"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffGridNode_right"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffGridNode_right"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffGridNode_up"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffGridNode_up"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffPacman"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffPacman"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffPositionableEntity_on"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffPositionableEntity_on"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_Game" ordered="false"
        upperBound="-1" eType="#//Pattern_Game"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_GridNode"
        ordered="false" upperBound="-1" eType="#//Pattern_GridNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_PositionableEntity"
        ordered="false" upperBound="-1" eType="#//Pattern_PositionableEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pattern__ListEInt">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rule">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraints" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_Pattern_SemanticObject"
        ordered="false" upperBound="-1" eType="#//Pattern_SemanticObject" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_Pattern_DiffEnergizer"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffEnergizer" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_Pattern_DiffFood"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffFood" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_Pattern_DiffFruit"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffFruit" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_Pattern_DiffGame"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffGame" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_Pattern_DiffGame_entities"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffGame_entities" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_Pattern_DiffGame_gridnodes"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffGame_gridnodes" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_Pattern_DiffGhost"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffGhost" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_Pattern_DiffGridNode"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffGridNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_Pattern_DiffGridNode_down"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffGridNode_down" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_Pattern_DiffGridNode_left"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffGridNode_left" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_Pattern_DiffGridNode_right"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffGridNode_right" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_Pattern_DiffGridNode_up"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffGridNode_up" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_Pattern_DiffPacman"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffPacman" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_Pattern_DiffPositionableEntity_on"
        ordered="false" upperBound="-1" eType="#//Pattern_DiffPositionableEntity_on"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_Pattern_Game"
        ordered="false" upperBound="-1" eType="#//Pattern_Game" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_Pattern_GridNode"
        ordered="false" upperBound="-1" eType="#//Pattern_GridNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_Pattern_PositionableEntity"
        ordered="false" upperBound="-1" eType="#//Pattern_PositionableEntity" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
