<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pacman" nsURI="http://www.zadahmad.org/dsmcompare/pacman" nsPrefix="pacman">
  <eClassifiers xsi:type="ecore:EClass" name="GridNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="up" eType="#//GridNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="down" eType="#//GridNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="left" eType="#//GridNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="right" eType="#//GridNode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Food" eSuperTypes="#//PositionableEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pacman" eSuperTypes="#//PositionableEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialPosition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ghost" eSuperTypes="#//PositionableEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="strategy" lowerBound="1"
        eType="#//GhostStrategy"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lives" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="score" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gridnodes" upperBound="-1"
        eType="#//GridNode" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//PositionableEntity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PositionableEntity" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="on" lowerBound="1" eType="#//GridNode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fruit" eSuperTypes="#//Food">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Energizer" eSuperTypes="#//Food">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="durations" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GhostStrategy">
    <eLiterals name="Blinky" literal="Blinky"/>
    <eLiterals name="Pinky" value="1" literal="Pinky"/>
    <eLiterals name="Inky" value="2"/>
    <eLiterals name="Clyde" value="3"/>
  </eClassifiers>
</ecore:EPackage>
