<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="deleteGhost_on_deleteGhost_on" nsURI="http://cdapackage/deleteGhost_on/deleteGhost_on/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#n2_n2:DiffPositionableEntity_on#"/>
    <eClassifiers xsi:type="ecore:EClass" name="n0_n0:Game">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#entities#" eType="#/0/n1_n1%3AGhost"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="n1_n1:Ghost"/>
  </ecore:EPackage>
  <ecore:EPackage name="deleteGhost_on_deleteGhost_on" nsURI="http://cdapackage/deleteGhost_on/deleteGhost_on/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#n2_n2:DiffPositionableEntity_on#"/>
  </ecore:EPackage>
  <ecore:EPackage name="deleteGhost_on_deleteGhost_on" nsURI="http://cdapackage/deleteGhost_on/deleteGhost_on/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#n2_n2:DiffPositionableEntity_on#"/>
    <eClassifiers xsi:type="ecore:EClass" name="n0_n0:Game">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#entities#" eType="#/2/n1_n1%3AGhost"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="n1_n1:Ghost"/>
  </ecore:EPackage>
  <ecore:EPackage name="deleteGhost_on_deleteGhost_on" nsURI="http://cdapackage/deleteGhost_on/deleteGhost_on/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="n0_n0:Game">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#entities#" eType="#/3/n1_n1%3AGhost"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="n1_n1:Ghost"/>
  </ecore:EPackage>
</xmi:XMI>
