<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="delete_Pacman_deletePacman_on" nsURI="http://cdapackage/delete_Pacman/deletePacman_on/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#n1_n1:DiffPacman#"/>
    <eClassifiers xsi:type="ecore:EClass" name="n0_n0:Game">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#entities#" eType="#/0/%23n1_n1%3ADiffPacman%23"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="deletePacman_on_delete_Pacman" nsURI="http://cdapackage/deletePacman_on/delete_Pacman/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="n0_n0:Game">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#entities#" eType="#/1/n1_n1%3ADiffPacman"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="n1_n1:DiffPacman"/>
  </ecore:EPackage>
</xmi:XMI>
