/**
 */
package pacmanDiffMM.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import pacmanDiffMM.util.PacmanDiffMMAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class PacmanDiffMMItemProviderAdapterFactory extends PacmanDiffMMAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public PacmanDiffMMItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM.ConflictResolution} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConflictResolutionItemProvider conflictResolutionItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM.ConflictResolution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConflictResolutionAdapter() {
		if (conflictResolutionItemProvider == null) {
			conflictResolutionItemProvider = new ConflictResolutionItemProvider(this);
		}

		return conflictResolutionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM.DiffEnergizer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffEnergizerItemProvider diffEnergizerItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM.DiffEnergizer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffEnergizerAdapter() {
		if (diffEnergizerItemProvider == null) {
			diffEnergizerItemProvider = new DiffEnergizerItemProvider(this);
		}

		return diffEnergizerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM.DiffFood} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffFoodItemProvider diffFoodItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM.DiffFood}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffFoodAdapter() {
		if (diffFoodItemProvider == null) {
			diffFoodItemProvider = new DiffFoodItemProvider(this);
		}

		return diffFoodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM.DiffFruit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffFruitItemProvider diffFruitItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM.DiffFruit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffFruitAdapter() {
		if (diffFruitItemProvider == null) {
			diffFruitItemProvider = new DiffFruitItemProvider(this);
		}

		return diffFruitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM.DiffGame} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffGameItemProvider diffGameItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM.DiffGame}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffGameAdapter() {
		if (diffGameItemProvider == null) {
			diffGameItemProvider = new DiffGameItemProvider(this);
		}

		return diffGameItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM.DiffGame_entities} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffGame_entitiesItemProvider diffGame_entitiesItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM.DiffGame_entities}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffGame_entitiesAdapter() {
		if (diffGame_entitiesItemProvider == null) {
			diffGame_entitiesItemProvider = new DiffGame_entitiesItemProvider(this);
		}

		return diffGame_entitiesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM.DiffGame_gridnodes} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffGame_gridnodesItemProvider diffGame_gridnodesItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM.DiffGame_gridnodes}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffGame_gridnodesAdapter() {
		if (diffGame_gridnodesItemProvider == null) {
			diffGame_gridnodesItemProvider = new DiffGame_gridnodesItemProvider(this);
		}

		return diffGame_gridnodesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM.DiffGhost} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffGhostItemProvider diffGhostItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM.DiffGhost}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffGhostAdapter() {
		if (diffGhostItemProvider == null) {
			diffGhostItemProvider = new DiffGhostItemProvider(this);
		}

		return diffGhostItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM.DiffGridNode} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffGridNodeItemProvider diffGridNodeItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM.DiffGridNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffGridNodeAdapter() {
		if (diffGridNodeItemProvider == null) {
			diffGridNodeItemProvider = new DiffGridNodeItemProvider(this);
		}

		return diffGridNodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM.DiffGridNode_down} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffGridNode_downItemProvider diffGridNode_downItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM.DiffGridNode_down}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffGridNode_downAdapter() {
		if (diffGridNode_downItemProvider == null) {
			diffGridNode_downItemProvider = new DiffGridNode_downItemProvider(this);
		}

		return diffGridNode_downItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM.DiffGridNode_left} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffGridNode_leftItemProvider diffGridNode_leftItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM.DiffGridNode_left}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffGridNode_leftAdapter() {
		if (diffGridNode_leftItemProvider == null) {
			diffGridNode_leftItemProvider = new DiffGridNode_leftItemProvider(this);
		}

		return diffGridNode_leftItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM.DiffGridNode_right} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffGridNode_rightItemProvider diffGridNode_rightItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM.DiffGridNode_right}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffGridNode_rightAdapter() {
		if (diffGridNode_rightItemProvider == null) {
			diffGridNode_rightItemProvider = new DiffGridNode_rightItemProvider(this);
		}

		return diffGridNode_rightItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM.DiffGridNode_up} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffGridNode_upItemProvider diffGridNode_upItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM.DiffGridNode_up}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffGridNode_upAdapter() {
		if (diffGridNode_upItemProvider == null) {
			diffGridNode_upItemProvider = new DiffGridNode_upItemProvider(this);
		}

		return diffGridNode_upItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM.DiffPacman} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffPacmanItemProvider diffPacmanItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM.DiffPacman}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffPacmanAdapter() {
		if (diffPacmanItemProvider == null) {
			diffPacmanItemProvider = new DiffPacmanItemProvider(this);
		}

		return diffPacmanItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM.DiffPositionableEntity_on} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffPositionableEntity_onItemProvider diffPositionableEntity_onItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM.DiffPositionableEntity_on}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffPositionableEntity_onAdapter() {
		if (diffPositionableEntity_onItemProvider == null) {
			diffPositionableEntity_onItemProvider = new DiffPositionableEntity_onItemProvider(this);
		}

		return diffPositionableEntity_onItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM.Energizer} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EnergizerItemProvider energizerItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM.Energizer}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEnergizerAdapter() {
		if (energizerItemProvider == null) {
			energizerItemProvider = new EnergizerItemProvider(this);
		}

		return energizerItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM.Food} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FoodItemProvider foodItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM.Food}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFoodAdapter() {
		if (foodItemProvider == null) {
			foodItemProvider = new FoodItemProvider(this);
		}

		return foodItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM.Fruit} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FruitItemProvider fruitItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM.Fruit}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createFruitAdapter() {
		if (fruitItemProvider == null) {
			fruitItemProvider = new FruitItemProvider(this);
		}

		return fruitItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM.Game} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GameItemProvider gameItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM.Game}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGameAdapter() {
		if (gameItemProvider == null) {
			gameItemProvider = new GameItemProvider(this);
		}

		return gameItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM.Ghost} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GhostItemProvider ghostItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM.Ghost}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGhostAdapter() {
		if (ghostItemProvider == null) {
			ghostItemProvider = new GhostItemProvider(this);
		}

		return ghostItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM.GridNode} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GridNodeItemProvider gridNodeItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM.GridNode}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGridNodeAdapter() {
		if (gridNodeItemProvider == null) {
			gridNodeItemProvider = new GridNodeItemProvider(this);
		}

		return gridNodeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM.Pacman} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PacmanItemProvider pacmanItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM.Pacman}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPacmanAdapter() {
		if (pacmanItemProvider == null) {
			pacmanItemProvider = new PacmanItemProvider(this);
		}

		return pacmanItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM.SemanticConflict} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SemanticConflictItemProvider semanticConflictItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM.SemanticConflict}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSemanticConflictAdapter() {
		if (semanticConflictItemProvider == null) {
			semanticConflictItemProvider = new SemanticConflictItemProvider(this);
		}

		return semanticConflictItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM.SemanticDiff} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SemanticDiffItemProvider semanticDiffItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM.SemanticDiff}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSemanticDiffAdapter() {
		if (semanticDiffItemProvider == null) {
			semanticDiffItemProvider = new SemanticDiffItemProvider(this);
		}

		return semanticDiffItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link pacmanDiffMM._ListEInt} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected _ListEIntItemProvider _ListEIntItemProvider;

	/**
	 * This creates an adapter for a {@link pacmanDiffMM._ListEInt}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter create_ListEIntAdapter() {
		if (_ListEIntItemProvider == null) {
			_ListEIntItemProvider = new _ListEIntItemProvider(this);
		}

		return _ListEIntItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (conflictResolutionItemProvider != null) conflictResolutionItemProvider.dispose();
		if (diffEnergizerItemProvider != null) diffEnergizerItemProvider.dispose();
		if (diffFoodItemProvider != null) diffFoodItemProvider.dispose();
		if (diffFruitItemProvider != null) diffFruitItemProvider.dispose();
		if (diffGameItemProvider != null) diffGameItemProvider.dispose();
		if (diffGame_entitiesItemProvider != null) diffGame_entitiesItemProvider.dispose();
		if (diffGame_gridnodesItemProvider != null) diffGame_gridnodesItemProvider.dispose();
		if (diffGhostItemProvider != null) diffGhostItemProvider.dispose();
		if (diffGridNodeItemProvider != null) diffGridNodeItemProvider.dispose();
		if (diffGridNode_downItemProvider != null) diffGridNode_downItemProvider.dispose();
		if (diffGridNode_leftItemProvider != null) diffGridNode_leftItemProvider.dispose();
		if (diffGridNode_rightItemProvider != null) diffGridNode_rightItemProvider.dispose();
		if (diffGridNode_upItemProvider != null) diffGridNode_upItemProvider.dispose();
		if (diffPacmanItemProvider != null) diffPacmanItemProvider.dispose();
		if (diffPositionableEntity_onItemProvider != null) diffPositionableEntity_onItemProvider.dispose();
		if (energizerItemProvider != null) energizerItemProvider.dispose();
		if (foodItemProvider != null) foodItemProvider.dispose();
		if (fruitItemProvider != null) fruitItemProvider.dispose();
		if (gameItemProvider != null) gameItemProvider.dispose();
		if (ghostItemProvider != null) ghostItemProvider.dispose();
		if (gridNodeItemProvider != null) gridNodeItemProvider.dispose();
		if (pacmanItemProvider != null) pacmanItemProvider.dispose();
		if (semanticConflictItemProvider != null) semanticConflictItemProvider.dispose();
		if (semanticDiffItemProvider != null) semanticDiffItemProvider.dispose();
		if (_ListEIntItemProvider != null) _ListEIntItemProvider.dispose();
	}

}
