package ca.umontreal.geodes.dsmcompare.dsmcHenshin

import java.io.File
import java.io.*
import java.util.ArrayList
import java.util.HashSet
import java.util.Stack
import org.eclipse.emf.common.util.URI
import org.eclipse.emf.ecore.EClass
import org.eclipse.emf.ecore.EObject
import org.eclipse.emf.ecore.EPackage
import org.eclipse.emf.ecore.EReference
import org.eclipse.emf.ecore.EStructuralFeature
import org.eclipse.emf.ecore.EcorePackage
import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.emf.ecore.resource.impl.ResourceSetImpl
import org.eclipse.emf.ecore.xmi.impl.EcoreResourceFactoryImpl
import ca.umontreal.geodes.dsmcompare.mmextension.utils.DsmcHelpers
import ca.umontreal.geodes.dsmcompare.mmextension.utils.DsmcHelpers.SrcRefTrgtMM

class MMToFineGrainedHenshinText {	 
	 Stack<SrcRefTrgtMM> 		stackRefTypes			= 	new Stack<SrcRefTrgtMM>();
	 ArrayList<EClass> 		    	allPathNodes           	= 	new ArrayList<EClass>();	
	 Stack<SrcRefTrgtMM> 	allPathEdges 			= 	new Stack<SrcRefTrgtMM>();
	 String						ruleSignature					=   "";		
	 EClass					root					= 	null;	
	 String						rulesDefinitionsAndCallsInSequntialStarUnit    			= 	"";		 			
	 String						callsStarUnits   				= 	"";		 			
	 String						DefinitionsStarUnits 			= 	"";		 
	 
	 public  String				dsmName					    	=	"";
	 public  String				rootClassName			    	=	"";
	 
	 public  String 			MM_eNSURI 						= 	"";  	
 	 public  Object 			MM_eIN	 						=	null; 	 
	 
	 public  String				mmFolderPath					=	"";
	 public  String				mmFileName					    =	"";
	 public  String				mmFilePath					    =	"";
	 
	 public  String				henshinFolderPath				=	"";
	 public  String				henshinFileName					=	"AutoGeneratedFineRules.henshin_text";	 
	 public  String				henshinFilePath					=	"";
	 
	 public  ArrayList<String>  edges							=   new ArrayList<String>();
	      
    //**************************************	
	def public void run(){
	 	henshinFilePath	=	henshinFolderPath + henshinFileName;	
	 	mmFilePath		=	mmFolderPath + mmFileName;
	 	generateAllFineGrainedRules()
	}

	def generateAllFineGrainedRules(){	  	 	
	    if(henshinFilePath!=""){
	    	//doEMFSetup	
		    var PrintWriter out = new PrintWriter(henshinFilePath); 
		    try{
			   // val resourceSet = new ResourceSetImpl
				//resourceSet.getPackageRegistry().put(MM_eNSURI, MM_eIN);
				//val resource = resourceSet.getResource(URI.createURI(mmFilePath), true)
				
				var ecoreModelFile = new File(mmFilePath);
				var resourceSet = new ResourceSetImpl();
				resourceSet.getPackageRegistry().put(EcorePackage.eNS_URI, EcorePackage.eINSTANCE);
				resourceSet.getResourceFactoryRegistry().getExtensionToFactoryMap().put("ecore", new EcoreResourceFactoryImpl());
				var resource = resourceSet.getResource(URI.createFileURI(ecoreModelFile.getAbsolutePath()), true);
				resource.load(null);
				    //var ecoreModel = (EPackage) resource.getContents().get(0);
				
				
				out.print(generatePackageImport(resource.contents.get(0) as EObject));				
				rulesDefinitionsAndCallsInSequntialStarUnit = "\n\t"+"unit unitSequntialStar(){";				
			    //val resourceSet = new ResourceSetImpl
			    //val resource = resourceSet.getResource(URI.createURI(mmFilePath), true)
				//1. Get the current Node
				//2. Calculate Path to current Node from root
				//	2.1 AllPathNodes
				//	2.2 AllPathEdges (Associations)
				//3. Create ADD/Delete rule for the Node
				//4. Create change rule for each attribute of the Node
				//5. Create ADD/DELTE for edge
			    
			    var ePackage = resource.contents.get(0) as EPackage;
			    var eClassifiers = ePackage.getEClassifiers()
			    var rootFound = false
			    for(c:eClassifiers){
			    	if(rootFound == false && c instanceof EClass){
				    	var cClass =c as EClass
				    	if(cClass.name.equals(rootClassName)){	//@@@It should be corrected
				    	//if(cClass.eClass().name=="EClass"){
				    		root = cClass
				    		rootFound = true
				    	}
			    	}
			    }
			    
			    var node = root;
			    var visitedRefs = new ArrayList<SrcRefTrgtMM>();
			    var visitedNodes = new HashSet<EClass>();
			    var Result="";
			    
			   do{
				    allPathNodes.add(node);	
				    //if not visitedNodes already contains (node)	
				    //1. out.print(generateRule(node ADD DELETE MODIFY));			    
				    //2. out.print(for each (node.getEAllAttributes() MODIFY))
				    out.print("\n"+node.getName())
					visitedNodes.add(node);	
				    var refTypes = getAllNodeAssocCollection_MM(node);
				    if(refTypes.size()>0){				    	
					    for(r:refTypes){		    				    	
					    	if(!isIn(r,visitedRefs)){
					    		stackRefTypes.push(r);					    		
					    		visitedRefs.add(r);					    		
					    	}					    	
					    }
				    }	
				    var top = stackRefTypes.peek();	
				    do{						    
				    	//3. out.print(eReference ADD DELETE))
				    	out.print("\n"+top.source.getName() + "-"+top.eReference.getName()+ "->"+top.target.getName())	
					    stackRefTypes.pop();
					    if(top!=null){
						    node = top.target;		
						    if(allPathEdges.size()>0 && allPathEdges.peek().source.equals(top.source)){
						    	allPathEdges.pop();
						    	allPathEdges.add(top);
						    }
						    else
						    	allPathEdges.add(top);	    
					    }else{//refTypes.size()==0
					    	node=null;
					    }
				    }while (visitedNodes.contains(node) && stackRefTypes.size()>0);// || (node==null && stackRefTypes.size()>0) );							    	    
			    } while(stackRefTypes.size()>0);
			    
			    //allPathNodes.clear();
			    //allPathEdges.clear();
			    rulesDefinitionsAndCallsInSequntialStarUnit += callsStarUnits;
			    rulesDefinitionsAndCallsInSequntialStarUnit += "\n\t}";
			    rulesDefinitionsAndCallsInSequntialStarUnit += DefinitionsStarUnits;
			    out.print(rulesDefinitionsAndCallsInSequntialStarUnit);
			    out.close; 		    
	    	}catch(Exception ex){
	    		System.out.print(ex.message); 
	    		out.close; 
	    	}		    
	    } 
	  }
	  
	 def doEMFSetup() {
		EPackage.Registry.INSTANCE.put(MM_eNSURI, MM_eIN)
		Resource.Factory.Registry.INSTANCE.extensionToFactoryMap.put("ecore", new EcoreResourceFactoryImpl);
		//extensionToFactoryMap.put("ecore", new EcoreResourceFactoryImpl());
	  }
	  
	  def boolean isIn(SrcRefTrgtMM r,ArrayList<SrcRefTrgtMM> visitedRefs){
	    	var i=0;
	    	while(i<visitedRefs.size()){
	    		var v=visitedRefs.get(i);
	    		i++;
	    		if(v.source.equals(r.source) && v.target.equals(r.target) && v.eReference.equals(r.eReference)){
    				return true;
	    		}					    			
	    	}
	    	return false;
	  }
	 
	 //***********************************************    
	 def dispatch generatePackageImport(EObject it) '''
ePackageImport  �eClass().getEPackage().getName() + ("DiffMM")�
	  '''
	  /*
	 def dispatch generateFineRules(EClass it) '''
	 			   �do�
	 				    �allPathNodes.add(it)�	
	 				    �it.getName()�
	 					�visitedNodes.add(node);�	
	 				    �var refTypes = getAllNodeAssocCollection_MM(node)�
	 				    �IF(refTypes.size()>0)�				    	
	 					    �FOR(r:refTypes)�	
	 					    	�IF(isIn(r,visitedRefs)�
	 					    		�stackRefTypes.push(r)�					    		
	 					    		�visitedRefs.add(r)�					    		
	 					    	�ENDIF�
	 					    �ENDFOR�	
	 					 �ENDIF�	
	 				    �var top = stackRefTypes.peek()�	
	 				    �do�					    
	 				    	�"\n"+top.source.getName() + "-"+top.eReference.getName()+ "->"+top.target.getName()�				    						    	
	 					    �stackRefTypes.pop()�
	 					    �if(top!=null)�
	 						    �node = top.target�		
	 						    �if(allPathEdges.size()>0 && allPathEdges.peek().source.equals(top.source))�
	 						    	�allPathEdges.pop()�
	 						    	�allPathEdges.add(top)�	 						    
	 						    �else�
	 						    	�allPathEdges.add(top)�	    
	 					    �else�
	 					    	�node=null�
	 				    �while (visitedNodes.contains(node) && stackRefTypes.size()>0)�							    	    
	 			    �while(stackRefTypes.size()>0)�
	 	  
//----------------------------------------------------------------------
	  '''	   */

	 def dispatch generateRule(EClass it) '''
		�init(it)��getRuleNodes()�
		�defineStarUnitForRule(EMFUtils.getAttrValueByAttrName(it,"name").toString()+"Post")�
		�callStarUnitForRule(EMFUtils.getAttrValueByAttrName(it,"name").toString()+"Post")�

		rule �EMFUtils.getAttrValueByAttrName(it,"name").toString()+""�(VAR nPostchangeStatus:EString, VAR nPostdiff_kind_Left:EString, VAR nPostdiff_kind_Right:EString)
		{
			graph
			{
			  	�FOR n : allPathNodes�
			  		�IF EMFUtils.getAttrValueByAttrName(n,"isForbidden") != true && EMFUtils.getAttrValueByAttrName(n,"Filter") != true�
							�defineNodePost(n, "preserve")�
			      	�ENDIF�
			  	�ENDFOR�
			�defineEdges()�
			�IF edges.size() > 0�
			edges[
		  		�FOR edg : edges�
		  			�IF !edg.contains("delete")�
					�"\t\t\t\t\t"+edg.replace("create","preserve")�
		      		�ENDIF�			  					  			
		  		�ENDFOR�
	      		 ]
			�ENDIF�		      		
			}
		}
//----------------------------------------------------------------------
	  '''
 
	 //***********************************************   
	 def void init(EClass Root){
 			allPathNodes    = 	new ArrayList<EClass>();	
		  	allPathEdges 	= 	new Stack<SrcRefTrgtMM>();
	 		root			=	Root;
	  		allPathNodes	=	DsmcHelpers.getAllNodesMM(root, true, false);
	 }
	 
	 def void getRuleNodes(){
	 	var sizeNodes = allPathNodes.size();
	 	var i=0;//i=0 is the root node, we will ignore it
	 	var j=0;
	 	var rmv = new ArrayList<EObject>();
	 	for(i=2;i<sizeNodes-1;i++){
	 		var parent 	=	allPathNodes.get(i-1); 
	 		if(!allPathNodes.get(i).eContainer().equals(parent) && !rmv.contains(parent)){
	 				rmv.add(parent);
	 		} 		
	 	}	 	
 		for(r:rmv){
 			allPathNodes.remove(r);
 		}
	 }
	 	 
	 def String defineWileLoopForRule(String ruleName){
	 		var wileLoopForRule = "while{\n\t\t\t";
		    wileLoopForRule +=ruleName+"()"
		    wileLoopForRule +="\n\t\t}";
	 }
	 
	 def void defineStarUnitForRule(String ruleName){
	 		var starUnitDefinitionForRule = "\n\t"+"unit unit"+ruleName+"Star(){\n\t\t";
		    starUnitDefinitionForRule +=defineWileLoopForRule(ruleName);
		    starUnitDefinitionForRule +="\n\t}";
		    DefinitionsStarUnits += starUnitDefinitionForRule;
	 }
	 
	 def void callStarUnitForRule(String ruleName){
	 		 callsStarUnits+= "\n\t\t"+"unit"+ruleName+"Star()";
	 }
	 
	 //***********************************************   
	 def String defineNodePost(EObject n, String actionText)
	 {	 
	 	var nodeDef="\t\t\t\t "+actionText;
	 	if(actionText == "preserve" || actionText == "forbid")
	 		nodeDef+= "\t\t\t";
	 		
	 	nodeDef += createNode(n)+":"+DsmcHelpers.getSuperClassName(n);	 	
		
		if(actionText == "preserve")
		{
			nodeDef += "{";	
	 		nodeDef += "\n\t\t\t\t\t" + "preserve	changeStatus 	= 	nPostchangeStatus";
	 		nodeDef += "\n\t\t\t\t\t" + "preserve	diff_kind_Left 	= 	nPostdiff_kind_Left";
	 		nodeDef += "\n\t\t\t\t\t" + "preserve	diff_kind_Right	= 	nPostdiff_kind_Right";
	 		nodeDef +="\n" + "\t\t\t\t}";	
	 	}	
	 		
	 	return nodeDef;	 	
	 }
	 
	 //***********************************************   
	 def String defineNode(EObject n, String actionText, String henshinFileType)
	 {
	 	var nodeDef="\t\t\t\t "+actionText;
	 	if(actionText == "preserve" || actionText == "forbid")
	 		nodeDef+= "\t\t\t"
	 	else
	 		nodeDef+= "\t\t\t\t"
	 	
	 	nodeDef += createNode(n)+":"+DsmcHelpers.getSuperClassName(n);
	 	
	 	var diffKindVal = "";
	 	var diffKindLeftDef= "";
	 	var diffKindRightDef= "";
	 	if(henshinFileType=="DSDiff"){
	 		diffKindVal = getStringAttrDef(n,"diff_kind");
	 		if(!diffKindVal.contains("NON")){
	 			diffKindLeftDef  = diffKindVal.replace("diff_kind","diff_kind_Left");	 
	 			diffKindRightDef  = diffKindVal.replace("diff_kind","diff_kind_Right");	
	 		}		
	 	}
	 		 	
	 	if(diffKindLeftDef != "" || diffKindRightDef !="" )
	 		{
	 		nodeDef += "{";	 		
	 		
	 		if(diffKindLeftDef!=""){
	 			nodeDef += "\n\t\t\t\t\t" + actionText + " " + diffKindLeftDef;
	 		}
	 		if(diffKindRightDef!=""){
	 			nodeDef += "\n\t\t\t\t\t" + actionText + " " + diffKindRightDef;
	 		}	 		
		 	nodeDef +="\n" + "\t\t\t\t}";	 	
	 	}
	 	
	 	return nodeDef;
	 } 
	 
	 def String getStringAttrDef(EObject n, String attrName)
	 {
	 	var attr= DsmcHelpers.getEAttributeByName(n,attrName);
	 	if(attr==null){
	 		return "";
	 	}	 		
	 	else{
	 		if(attr.getEAttributeType().eClass().getName().toLowerCase()=="eenum"){	
	 			var id_PatternLhs=DsmcHelpers.getAttrValueByAttrName(n,"ID_Pattern").toString();			
				return  attrName +" = " + "n" + id_PatternLhs + attrName;	 		}
	 		else{
	 			return attrName + " = " + "\"\\\"" + n.eGet(attr).toString()+ "\\\"\"";
	 		}
	 	}
	 }
	 
	 def void defineEdges(){
	  	edges= new ArrayList<String>();
	  	for(SrcRefTrgtMM ERefC: getAllAssocCollection_MM()){
	  		if(allPathNodes.contains(ERefC.source) && allPathNodes.contains(ERefC.target))
	  		{ 		 
		  		if((DsmcHelpers.getAttrValueByAttrName(ERefC.source,"ID_Pattern").toString().contains("-") == true)
		  			||  (DsmcHelpers.getAttrValueByAttrName(ERefC.target,"ID_Pattern").toString().contains("-") == true))
		  		{
		  			var AssocDef= 	
		  						"("+
		  						"create\t\t" + 
		  						createNodeNumber(ERefC.source)+
		  						"->" + 
		  						createNodeNumber(ERefC.target)+
		  						":"+
		  						ERefC.eReference.getName()+
		  						"),";
					edges.add(AssocDef);
		  		}
		  		else if(!ERefC.source.eClass().getName().toLowerCase().contains("domainspecificdiff"))
		  		{
		  			var AssocDef= 	
		  						"("+
		  						"preserve\t" + 
		  						createNodeNumber(ERefC.source)+
		  						"->" + 
		  						createNodeNumber(ERefC.target)+
		  						":"+
		  						ERefC.eReference.getName()+
		  						"),";
					edges.add(AssocDef);
		  		}
	  		}   		
		}
		if(edges.size()>0)	 
		{
	  		var s =edges.get(edges.size()-1);
	  		s= s.substring(0, s.length() - 1);
	  		edges.set(edges.size()-1,s);
		}
	  }

	 def Boolean addParamToRuleSignature(String param){
	  	if(param!=null && param!="" && !ruleSignature.contains(param)){
			if(ruleSignature!="" && ruleSignature!=null)
			 	{ ruleSignature += "," + param; }
			else 
			 	{ ruleSignature += param; }	
			return true;	
		}
		return false;	 	
	 }
	  
	 //***********************************************   
	 def String createNode(EObject n)
	 {
	 	return "node " + createNodeNumber(n);
	 }	 
	 
	 def String createNodeNumber(EObject n)
	 {
	 	return "n" + DsmcHelpers.getAttrValueByAttrName(n,"ID_Pattern").toString().replace("-","").trim();
	 }

	 //***********************************************   
	 def Stack<SrcRefTrgtMM> getAllAssocCollection_MM()
	 {	
	  	for(EClass node: allPathNodes){
	  		var nodeAssocCollection = getAllNodeAssocCollection_MM(node);
	  		if(nodeAssocCollection.size()>0){
	  			allPathEdges.addAll(nodeAssocCollection);
	  		}	  		
	  	}
	  	
	  	return allPathEdges;
	 }
	  
	 def HashSet<SrcRefTrgtMM> getAllNodeAssocCollection_MM(EClass src)
	 {
	  	var allNodeAssociations = new HashSet<SrcRefTrgtMM>();		  	
		var features = new ArrayList<EStructuralFeature>(src.getEStructuralFeatures());
		for (EStructuralFeature r : features) {
			if(r instanceof  EReference){			
				  try{
		  			var AllTargets= DsmcHelpers.getAllTargetsMM(src,r);
		  			
			  		if(AllTargets !== null && AllTargets.size()>0){
				  		for (EClass target:AllTargets){
				  			var newERef= new SrcRefTrgtMM(src,r,target);
				  			allNodeAssociations.add(newERef);
				  			var subClasses = DsmcHelpers.getAllSubClassesMM(target);
				  			for (EClass sc:subClasses){				  				
				  			var newERef2= new SrcRefTrgtMM(src,r,sc);
				  			allNodeAssociations.add(newERef2);
				  			}				  			
				  		}
			  		}
		  		}catch(Exception ex){	  			
		  		}	  		
	  		}
	  	}
	  	
	  	
	  	
	  	
	  	
	  	return allNodeAssociations;
	 }	 
}








