package com.zadahmad.dsemfcompare.editor.dsmcHenshin;

//PrintWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.EmptyStackException;
import java.util.HashSet;
import java.util.List;
import java.util.Stack;
import java.util.stream.Collectors;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EClassifier;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.emf.ecore.EcorePackage;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.impl.ResourceSetImpl;
import org.eclipse.emf.ecore.xmi.impl.EcoreResourceFactoryImpl;
import org.eclipse.emf.henshin.interpreter.impl.EGraphImpl;
import org.eclipse.emf.henshin.interpreter.impl.EngineImpl;
import org.eclipse.emf.henshin.model.Rule;
import org.eclipse.emf.henshin.model.Unit;
import org.eclipse.emf.henshin.model.resource.HenshinResourceSet;

import com.google.common.collect.BiMap;
import com.google.common.collect.HashBiMap;
import com.zadahmad.dsemfcompare.editor.verstexSorting.DijkstraSP;
import com.zadahmad.dsemfcompare.editor.verstexSorting.DirectedEdge;
import com.zadahmad.dsemfcompare.editor.verstexSorting.EdgeWeightedDigraph;
import com.zadahmad.dsemfcompare.editor.verstexSorting.StdOut;

import dsmcompare.mmextension.utils.EMFUtils;
import dsmcompare.mmextension.utils.EMFUtils.SrcRefTrgtMM;

public class MMFineDiffRulesHenshinText
{	 
	 Stack<SrcRefTrgtMM> 		inStockSrcRefTrgtMMs			= 	new Stack<SrcRefTrgtMM>();
	 ArrayList<EClass> 		    nodes           				= 	new ArrayList<EClass>();	
	 Stack<SrcRefTrgtMM> 		allPathEdges 					= 	new Stack<SrcRefTrgtMM>();
	 BiMap<EClass,Integer> 		mapNodeId;
	 String						ruleSignature					=   "";		
	 EClass						root							= 	null;	
	 String						rulesDefinitionsAndCallsInSequntialStarUnit    			= 	"";		 			
	 String						callsStarUnits   				= 	"";		 			
	 String						DefinitionsStarUnits 			= 	"";		 
	 
	 public  String				dsmName					    	=	"";
	 public  String				rootClassName			    	=	"";
	 
	 public  String 			MM_eNSURI 						= 	"";  	
 	 public  Object 			MM_eIN	 						=	null; 	 
	 
	 public  String				mmFolderPath					=	"";
	 public  String				mmFileName					    =	"";
	 public  String				mmFilePath					    =	"";
	 
	 public  String				henshinFolderPath				=	"";
	 public  String				henshinTextFileName				=	"";//"AutoGeneratedFineRules.henshin_text";	 
	 public  String				henshinFileName					=   "";//"AutoGeneratedFineRules_henshin_text.henshin";
	 public  String 			transformedModelFilePath		= 	"";//"D:\\_udemSVN\\DSMCompare-Project\\srcCode\\DSMCompare\\com.Zadahmad.DSEMFCompare.editor\\DSMMerge\\dsdiffafterruningatest\\DSMDiff_transformed_transformed.xmi";

	 public  String				henshinTextFilePath				=	"";
	 public  String				henshinFilePath					=	"";
	 
	 public  ArrayList<String>  edges							=   new ArrayList<String>();
	 		 PrintWriter 		out;
	      
    //**************************************
	 public void correctChangeRules() {
		 henshinFilePath	=	henshinFolderPath + henshinFileName;	
		 mmFilePath			=	mmFolderPath + mmFileName;
		 	
		 transform(transformedModelFilePath, henshinFilePath);		 	
	 }
	 
	 public	void transform(String sourceModelPath, String henshinPath){
		//var sourceModel = new File(sourceModelPath);
		var henshinModel = new File(henshinPath);
			
		transform(henshinModel);	//sourceModel, 
	 }
		
	 public void transform(File henshinModel){//File sourceModel, 

		//			var reg = Resource.Factory.Registry.INSTANCE;
		//	        var m = reg.getExtensionToFactoryMap();
		//	        m.put("pnml", new PetriNetResourceFactoryImpl());

		EObject model = loadModel(henshinModel.getParent(), henshinModel.getName());

			
		var resourceSet = new HenshinResourceSet(henshinModel.getParent());
		
		var module = resourceSet.getModule(henshinModel.getName());
		
		//var model = resourceSet.getResource(sourceModel.getName());
		
		var engine = new EngineImpl();
		var graph = new EGraphImpl(model);
		
		
		
		//var unit = (Rule) module.getUnit("changeGamescore");
		EList<Unit> units=module.getUnits();
		for(Unit unit:units) {
			try {
				var r = (Rule) unit;
				if(r.getName().startsWith("change")) {
					var a = r.getLhs().getNodes().get(0).getAttributes().get(0);
					var v = a.getValue();
					var t=a.getType();
					if(t.getEType().getName().toLowerCase().contains("string"))
						v="\"NON\"";
					else if(v.contains("+1"))
						v = a.getValue().replace("+1", "");
					else if(t.getName().toLowerCase().contains("enum"))
						v="NON";
					else v="";
					a.setValue(v);
				}				
			}catch(Exception ex) {
				
			}
			
		}
		
		//var application = new UnitApplicationImpl(engine, graph, unit, null);
		//var application = new RuleApplicationImpl(engine, graph, unit, null);
		
		//application.execute(new LoggingApplicationMonitor());
					
		//System.out.println(model);
			
		try {
			resourceSet.getResources().get(0).save(null);
			//model.eResource().save(null);
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	 }
	 		 
	 public HenshinResourceSet getResourceSet(String resourceSetPath) {

			return new HenshinResourceSet(resourceSetPath);
	}	 
	 
	 public EObject loadModel(String resourceSetPath, String modelFilePath) {
			
			Resource resource = getResourceSet(resourceSetPath).createResource(URI.createURI(modelFilePath));
			
			try {
				
				resource.load(Collections.EMPTY_MAP);
				return resource.getAllContents().next();
			
			}catch (Exception e) {
				
			}
		
			return null;
	}
	//************************************** 		 
	 		 
	public void run(){
	 	henshinTextFilePath	=	henshinFolderPath + henshinTextFileName;	
	 	mmFilePath		=	mmFolderPath + mmFileName;
	 	generateAllFineGrainedRules();
	}

	public void  generateAllFineGrainedRules(){	  	 	
	    if(henshinTextFilePath!=""){
			try {
				out = new PrintWriter(henshinTextFilePath);
			} catch (FileNotFoundException e) {
				e.printStackTrace();
			} 
		    try{				
				var ecoreModelFile = new File(mmFilePath);
				var resourceSet = new ResourceSetImpl();
				resourceSet.getPackageRegistry().put(EcorePackage.eNS_URI, EcorePackage.eINSTANCE);
				resourceSet.getResourceFactoryRegistry().getExtensionToFactoryMap().put("ecore", new EcoreResourceFactoryImpl());
				var resource = resourceSet.getResource(URI.createFileURI(ecoreModelFile.getAbsolutePath()), true);
				resource.load(null);
				EPackage ePackage = (EPackage)resource.getContents().get(0);				
				out.println(generatePackageImport(ePackage.getName()));				
				//rulesDefinitionsAndCallsInSequntialStarUnit = "\n\t"+"unit unitSequntialStar(){";	
				//1. Get the current Node
				//2. Calculate Path to current Node from root
				//	2.1 AllPathNodes
				//	2.2 AllPathEdges (Associations)
				//3. Create ADD/Delete rule for the Node
				//4. Create change rule for each attribute of the Node
				//5. Create ADD/DELTE for edge		    
				
				EList<EClassifier> eClassifiers = ePackage.getEClassifiers();
				root=findRoot(eClassifiers);
				ArrayList<SrcRefTrgtMM> processedSrcRefTrgtMMs = getUniqueSrcRefTrgt();	
				
			   	mapNodeId=mapToId();			   	
				EdgeWeightedDigraph G= createDigraph(processedSrcRefTrgtMMs, mapNodeId);
		        int startNodeIndex=mapNodeId.get(root);
				DijkstraSP dij=calculateShortestPathForEachEClass(G, startNodeIndex);
				printShortestPath(dij, G, mapNodeId, startNodeIndex, processedSrcRefTrgtMMs, out);		  
		        
			   	//Find Shortest Path for each DiffEClass and DiffReference from Which we will create the rules 
			    //rulesDefinitionsAndCallsInSequntialStarUnit += callsStarUnits;
			    //rulesDefinitionsAndCallsInSequntialStarUnit += "\n\t}";
			    //rulesDefinitionsAndCallsInSequntialStarUnit += DefinitionsStarUnits;
			    //out.print(rulesDefinitionsAndCallsInSequntialStarUnit);
			    out.close(); 		    
	    	}catch(Exception ex){
	    		System.out.print(ex.getMessage()); 
	    		out.close(); 
	    	}		    
	    } 
	  }
	
	public BiMap<EClass,Integer> mapToId() {
		int i=0;
	   	BiMap<EClass,Integer> mapNodeId=HashBiMap.create();
	   	for(EClass c:nodes) {
	   		mapNodeId.put(c,i);
	   		i+=1;
	   	}
	   	return mapNodeId;
	}
	
	public void printShortestPath(DijkstraSP dij,EdgeWeightedDigraph G,
			BiMap<EClass,Integer> mapNodeId, int startNodeIndex, ArrayList<SrcRefTrgtMM> processedSrcRefTrgtMMs, PrintWriter out) {
		for (Integer t = 0; t < G.V(); t++) {
            EClass eclassT = ((EClass)mapNodeId.inverse().get(t));
            String eclassTName = eclassT.getName();
			try {
	            if (eclassT.isAbstract()==false && dij.hasPathTo(t)) {

	            	ArrayList<Integer> path= new ArrayList<Integer>();
	            	path.add(startNodeIndex);
	                for (DirectedEdge e : dij.pathTo(t)) {
		            	path.add(e.to());
	                }
	                int pathSize=path.size();
	                
	                //String signatur="VAR n%sdiff_kind_Left:EString,VAR n%sdiff_kind_Right:EString".replaceAll("%s", t.toString());
	                String diffKindLeft="diff_kind_Left = n%sdiff_kind_Left".replaceAll("%s", t.toString());
	                String diffKindRight="diff_kind_Right = n%sdiff_kind_Right".replaceAll("%s", t.toString());
	                //String conditionADD="conditions [(n%sdiff_kind_Left == \"\\\"ADD\\\"\") OR (n%sdiff_kind_Right == \"\\\"ADD\\\"\")]".replaceAll("%s", t.toString());
	                //String conditionDELETE="conditions [(n%sdiff_kind_Left == \"\\\"DELETE\\\"\") OR (n%sdiff_kind_Right == \"\\\"DELETE\\\"\")]".replaceAll("%s", t.toString());
	                List<SrcRefTrgtMM>  	srts  = new ArrayList<SrcRefTrgtMM>();
	                ArrayList<EReference> 	refs  = new ArrayList<EReference>();
	                ArrayList<String> 		edges = new ArrayList<String>();	                
	                //String diffKindPrint="";
	                //diffKindPrint+="\t\t\t {\n";
	                //diffKindPrint+=String.format("\t\t\t\t %s\t%s\n", "preserve",diffKindLeft);
	                //diffKindPrint+=String.format("\t\t\t\t %s\t%s\n", "preserve",diffKindRight);
	                //diffKindPrint+="\t\t\t }\n";
	                
	                
	                //*********************************** CLASS DELETE
	                String action = "delete"; 
	            	out.printf("\n\t rule delete_"+eclassTName+"(){\n");
	            	out.println("\t\t graph{");
	                for(int i=0; i<pathSize-1;i++)
	                	out.println("\t\t\t preserve	node n"+(i)+":"+((EClass)mapNodeId.inverse().get(path.get(i))).getName());	                
	                out.println("\t\t\t delete	node n"+(pathSize-1)+":Diff"+eclassTName);
	                edges = createEdgeList(path, processedSrcRefTrgtMMs, action, pathSize-1);
	                String edgePrint = createEdgePrint(edges);
	                out.println(edgePrint);	                
	                out.println("\t\t }");
	                out.println("\t }");
	                
	                //*********************************** ATTRIBUTE CHNAGE
	                //Attribute change
	                for(EAttribute a:eclassT.getEAllAttributes()) {	                	
	                	if(a.isID()==false && a.getName().contains("diff_kind")==false && a.getName().contains("ChangeStatus")==false) {	                	
		                	//String attrChangeStatus=a.getName()+"ChangeStatus";
		                	//String varChangeStatus="n"+t+attrChangeStatus;
		                	//String signature="VAR "+varChangeStatus+":"+a.getEType().getName();
	                		String varAttr="n"+t+a.getName();
	                		boolean isEnum = a.getEType().eClass().getName().toLowerCase().equals("eenum");
	                		boolean isString = a.getEType().getName().toLowerCase().equals("estring");
	                		String valAttr=String.format("%s",isEnum?"\"CONTRADICTING\"":isString?"\"\\\"CONTRADICTING\\\"\"":varAttr+"+1");//String.format("'%s>%s+1'",varAttr,varAttr);//It works only for EInt
	                		String aSignature="VAR "+varAttr+":"+(isEnum||isString?"EString":a.getEType().getName());
			            	out.printf("\n\t rule change"+eclassTName+"_"+a.getName()+"(%s){\n",aSignature);
			            	out.println("\t\t graph{");
			                for(int i=0; i<pathSize-1;i++)
			                	out.println("\t\t\t preserve	node n"+(i)+":"+((EClass)mapNodeId.inverse().get(path.get(i))).getName());	                
			                out.println("\t\t\t preserve	node n"+(pathSize-1)+":Diff"+eclassTName);
			                out.println("\t\t\t {");
			                out.printf("\t\t\t\tpreserve %s = %s\n", a.getName(),valAttr);
			                //out.printf("\t\t\t\tpreserve %s = %s\n", attrChangeStatus,varChangeStatus);
			                out.println("\t\t\t }");
			                out.println(edgePrint);
			                out.println("\t\t }");	
			                out.println("\t }");	    
	                	}
	                }
	                
	                //*********************************** EReference Diff ADD	                
	                for(EReference r:eclassT.getEAllReferences()) {
	                	EClass eClass=(EClass)mapNodeId.inverse().get(t);
	                	String subClassName=eClass.getName();
	                	EList<EClass> superTypes = eClass.getEAllSuperTypes();
	                	if(superTypes.size()>0) {
	                		for(EClass s:superTypes)
	                			if(s.getEReferences().stream().filter(f->f.getName().equals(r.getName())).findFirst() != null) {
	                				eClass=s;
	                				break;
	                			}	
	                	}

	                	String superClassName=eClass.getName();
	                	//EReference Diff ADD
		                action = "create";
		                out.printf("\n\t rule add"+subClassName+"_"+r.getName()+"(){\n");
		            	out.println("\t\t graph{");
		            	for(int i=0; i<pathSize;i++)
		                	out.println("\t\t\t preserve	node n"+(i)+":"+((EClass)mapNodeId.inverse().get(path.get(i))).getName());	                
		                String ereferenceDiffClass = "Diff"+superClassName+"_"+r.getName();
		                out.println("\t\t\t create	node n"+(pathSize)+":"+ ereferenceDiffClass);
		                edges = createEdgeList(path, processedSrcRefTrgtMMs, action, pathSize-1);
		                edgePrint = createEdgePrint(edges);
		                edgePrint.replaceAll(subClassName, superClassName);
		                out.println(edgePrint);	
		                out.println("\t\t }");
		                out.println("\t }");
		                
		              //EReference Diff DELETE  
		                action = "delete";
		            	out.printf("\n\t rule delete"+subClassName+"_"+r.getName()+"(){\n");
		            	out.println("\t\t graph{");
		                for(int i=0; i<pathSize;i++)
		                	out.println("\t\t\t preserve	node n"+(i)+":"+((EClass)mapNodeId.inverse().get(path.get(i))).getName());	                
		                //ereferenceDiffClass = "Diff"+superClassName+"_"+r.getName();
		                out.println("\t\t\t delete	node n"+(pathSize)+":"+ ereferenceDiffClass);		                edges = createEdgeList(path, processedSrcRefTrgtMMs, action, pathSize-1);
		                edgePrint = createEdgePrint(edges);
		                edgePrint.replaceAll(subClassName, superClassName);
		                out.println(edgePrint);
		                out.println("\t\t }");
		                out.println("\t }");
	                }	                
	                
	            }
	            else {
	                StdOut.printf("%s to %s         no path\n", 
	                		((EClass)mapNodeId.inverse().get(startNodeIndex)).getName(), eclassTName);
	            }
			}catch(Exception ex) {}
        }
	}
	
	protected ArrayList<String> createEdgeList(ArrayList<Integer> path, 
			ArrayList<SrcRefTrgtMM> processedSrcRefTrgtMMs, String action, int actionNodeId){
		int pathSize = path.size();
		ArrayList<String>  edges= new ArrayList<String>();
		List<SrcRefTrgtMM>  srts= new ArrayList<SrcRefTrgtMM>();
        ArrayList<EReference> refs= new ArrayList<EReference>();
		for(int i=0; i<pathSize-1;i++) {
        	EClass source=(EClass)mapNodeId.inverse().get(path.get(i));
        	EClass target=(EClass)mapNodeId.inverse().get(path.get(i+1));
        	srts= processedSrcRefTrgtMMs.stream().filter(
        			f->f.source==source && f.target==target).collect(Collectors.toList());
        	srts.forEach(f->refs.add(f.eReference));
        	//Simple
        	//get the first reference
        	//add a reference
        	//edges[(preserve	n0->n1:gridnodes), (delete		n31->n1:eType),...]
        	if(i==actionNodeId || (i+1)==actionNodeId)
        		edges.add(String.format("(%s	n"+ i +"->n"+(i+1)+":"+refs.get(0).getName()+")",action));	
        	else
        		edges.add("(preserve	n"+ i +"->n"+(i+1)+":"+refs.get(0).getName()+")");	 
        	refs.clear();
        	//Complex
        	//for each reference of each source-target  
        	//create a rule
        }
		return edges;
	}
	
	protected String createEdgePrint(ArrayList<String> edges) {
		String edgePrint="";
        if(edges.size()>0) {
        	edgePrint+=("\t\t edges["+"\n");
            for(int i=0;i<edges.size()-1;i++)
            	edgePrint+=("\t\t\t\t "+edges.get(i)+","+"\n");
            edgePrint+=("\t\t\t\t "+edges.get(edges.size()-1)+"\n");		                
            edgePrint+=("\t\t\t ]"+"\n");
        }
        return edgePrint;
    }
	
	public EdgeWeightedDigraph createDigraph(ArrayList<SrcRefTrgtMM> processedSrcRefTrgtMMs, BiMap<EClass,Integer> mapNodeId) {
		/*
	 	for(SrcRefTrgtMM t:processedSrcRefTrgtMMs) {
	   		if(t.source!=null && t.eReference!=null && t.target!=null)
	   			out.println("ERef Poped: "+t.source.getName() + "-"+t.eReference.getName()+ "->"+t.target.getName());
	   		else
	   			out.println("ERef Poped: "+t.source.getName());			   	
	   	}
	   	*/
	 	
	   	int[][] Matrix = new int[processedSrcRefTrgtMMs.size()-1][3];

	   	try {
		   	int i=0;
		   	for(SrcRefTrgtMM srt:processedSrcRefTrgtMMs) {	
		   		if(srt.target!=null) {
			   		Matrix[i][0]=mapNodeId.get(srt.source);
			   		Matrix[i][1]=mapNodeId.get(srt.target);
			   		Matrix[i][2]=1;
			   		i+=1;
		   		}
		   	}	
	   	}
	   	catch(Exception ex) {
	   		
	   	}
	   	
	   	int vertexNumber=mapNodeId.size();			   	
        EdgeWeightedDigraph G = new EdgeWeightedDigraph(Matrix, vertexNumber);
        return G;
	}
	
	public DijkstraSP calculateShortestPathForEachEClass(EdgeWeightedDigraph G, int startNodeIndex) {
        DijkstraSP dij=new DijkstraSP(G, startNodeIndex);
        return dij;
	}
	
	public EClass findRoot(EList<EClassifier> eClassifiers) {
	    for(EClassifier c:eClassifiers)
	    	if(c instanceof EClass){
		    	var cClass =(EClass) c;
		    	if(cClass.getName().equals(rootClassName)){	//@@@It should be corrected
		    		return cClass;
		    	}
	    	}
	    return null;
	}
	
	public ArrayList<SrcRefTrgtMM> getUniqueSrcRefTrgt() {
		var currentNode = root;
	    var visitedSrcRefTrgtMMs = new HashSet<SrcRefTrgtMM>();
	    var visitedNodes = new HashSet<EClass>();	    
	    ArrayList<SrcRefTrgtMM> processedSrcRefTrgtMMs= new ArrayList<SrcRefTrgtMM>();
	    processedSrcRefTrgtMMs.add(new SrcRefTrgtMM(root,null,null));
	    
	    SrcRefTrgtMM top = null;
	    //out.println("ERef: "+node.getName());
	   do{
		    nodes.add(currentNode);	
			visitedNodes.add(currentNode);	
			var srcRefTrgtMMs = getAllNodeAssocCollection_MM(currentNode);
		    if(srcRefTrgtMMs.size()>0){				    	
			    for(SrcRefTrgtMM r:srcRefTrgtMMs){		    				    	
			    	if(!isVisited(r,visitedSrcRefTrgtMMs)){
			    		inStockSrcRefTrgtMMs.push(r);					    		
			    		visitedSrcRefTrgtMMs.add(r);	  				    		
			    	}					    	
			    }
		    }					    
		    do{	
		    	try {
		    	top = inStockSrcRefTrgtMMs.peek();	
			    processedSrcRefTrgtMMs.add(top);
		    	//3. out.print(eReference ADD DELETE))
		    	//out.println("ERef Poped: "+top.source.getName() + "-"+top.eReference.getName()+ "->"+top.target.getName());
			    inStockSrcRefTrgtMMs.pop();
			    currentNode=null;
			    if(top!=null)
				    currentNode = top.target;	
		    	}catch(EmptyStackException ex) {
		    		currentNode=null;
		    		break;
		    	}
		    }while (visitedNodes.contains(currentNode) && inStockSrcRefTrgtMMs.size()>0);// || (node==null && stackRefTypes.size()>0) );							    	    
	   }while(currentNode!=null);//inStockSrcRefTrgtMMs.size()>0);
	   return processedSrcRefTrgtMMs;
	}
	  
	public boolean isVisited(SrcRefTrgtMM r,HashSet<SrcRefTrgtMM> visitedRefs){
    	var vRs=visitedRefs.toArray();
    	for(int i=0;i<vRs.length;i++){
    		SrcRefTrgtMM v=(SrcRefTrgtMM) vRs[i];
    		i++;
    		if(v.source.equals(r.source) && v.target.equals(r.target) && v.eReference.equals(r.eReference)){
				return true;
    		}					    			
    	}
    	return false;
  }
	 
	 //***********************************************    
	 public String generatePackageImport(String ePackageName) { 
	 	return "ePackageImport  "+ePackageName + "DiffMM";
	 }

	 //***********************************************   
	 public void init(EClass Root){
 			nodes    = 	new ArrayList<EClass>();	
		  	allPathEdges 	= 	new Stack<SrcRefTrgtMM>();
	 		root			=	Root;
	  		nodes	=	EMFUtils.getAllNodesMM(root, true, false);
	 }
	 
	 public void getRuleNodes(){
		int sizeNodes = nodes.size();
		int i=0;//i=0 is the root node, we will ignore it
		int j=0;
		ArrayList<EObject> rmv = new ArrayList<EObject>();
	 	for(i=2;i<sizeNodes-1;i++){
	 		var parent 	=	nodes.get(i-1); 
	 		if(!nodes.get(i).eContainer().equals(parent) && !rmv.contains(parent)){
	 				rmv.add(parent);
	 		} 		
	 	}	 	
 		for(EObject r:rmv){
 			nodes.remove(r);
 		}
	 }
	 	 
	 public String defineWileLoopForRule(String ruleName){
		 String wileLoopForRule = "while{\n\t\t\t";
		 wileLoopForRule +=ruleName+"()";
		 wileLoopForRule +="\n\t\t}";
		 return wileLoopForRule;	    
	 }
	 
	 public void defineStarUnitForRule(String ruleName){
	 		var starUnitDefinitionForRule = "\n\t"+"unit unit"+ruleName+"Star(){\n\t\t";
		    starUnitDefinitionForRule +=defineWileLoopForRule(ruleName);
		    starUnitDefinitionForRule +="\n\t}";
		    DefinitionsStarUnits += starUnitDefinitionForRule;
	 }
	 
	 public void callStarUnitForRule(String ruleName){
	 		 callsStarUnits+= "\n\t\t"+"unit"+ruleName+"Star()";
	 }
	 
	 //***********************************************   
	 public String defineNodePost(EObject n, String actionText)
	 {	 
	 	var nodeDef="\t\t\t\t "+actionText;
	 	if(actionText == "preserve" || actionText == "forbid")
	 		nodeDef+= "\t\t\t";
	 		
	 	nodeDef += createNode(n)+":"+EMFUtils.getSuperClassName(n);	 	
		
		if(actionText == "preserve")
		{
			nodeDef += "{";	
	 		nodeDef += "\n\t\t\t\t\t" + "preserve	changeStatus 	= 	nPostchangeStatus";
	 		nodeDef += "\n\t\t\t\t\t" + "preserve	diff_kind_Left 	= 	nPostdiff_kind_Left";
	 		nodeDef += "\n\t\t\t\t\t" + "preserve	diff_kind_Right	= 	nPostdiff_kind_Right";
	 		nodeDef +="\n" + "\t\t\t\t}";	
	 	}	
	 		
	 	return nodeDef;	 	
	 }
	 
	 //***********************************************   
	 public String defineNode(EObject n, String actionText, String henshinFileType)
	 {
	 	var nodeDef="\t\t\t\t "+actionText;
	 	if(actionText == "preserve" || actionText == "forbid")
	 		nodeDef+= "\t\t\t";
	 	else
	 		nodeDef+= "\t\t\t\t";
	 	
	 	nodeDef += createNode(n)+":"+EMFUtils.getSuperClassName(n);
	 	
	 	var diffKindVal = "";
	 	var diffKindLeftDef= "";
	 	var diffKindRightDef= "";
	 	if(henshinFileType=="DSDiff"){
	 		diffKindVal = getStringAttrDef(n,"diff_kind");
	 		if(!diffKindVal.contains("NON")){
	 			diffKindLeftDef  = diffKindVal.replace("diff_kind","diff_kind_Left");	 
	 			diffKindRightDef  = diffKindVal.replace("diff_kind","diff_kind_Right");	
	 		}		
	 	}
	 		 	
	 	if(diffKindLeftDef != "" || diffKindRightDef !="" )
	 		{
	 		nodeDef += "{";	 		
	 		
	 		if(diffKindLeftDef!=""){
	 			nodeDef += "\n\t\t\t\t\t" + actionText + " " + diffKindLeftDef;
	 		}
	 		if(diffKindRightDef!=""){
	 			nodeDef += "\n\t\t\t\t\t" + actionText + " " + diffKindRightDef;
	 		}	 		
		 	nodeDef +="\n" + "\t\t\t\t}";	 	
	 	}
	 	
	 	return nodeDef;
	 } 
	 
	 public String getStringAttrDef(EObject n, String attrName)
	 {
	 	var attr= EMFUtils.getEAttributeByName(n,attrName);
	 	if(attr==null){
	 		return "";
	 	}	 		
	 	else{
	 		if(attr.getEAttributeType().eClass().getName().toLowerCase()=="eenum"){	
	 			var id_PatternLhs=EMFUtils.getAttrValueByAttrName(n,"ID_Pattern").toString();			
				return  attrName +" = " + "n" + id_PatternLhs + attrName;	 		}
	 		else{
	 			return attrName + " = " + "\"\\\"" + n.eGet(attr).toString()+ "\\\"\"";
	 		}
	 	}
	 }
	 
	 public void defineEdges(){
	  	edges= new ArrayList<String>();
	  	for(SrcRefTrgtMM ERefC: getAllAssocCollection_MM()){
	  		if(nodes.contains(ERefC.source) && nodes.contains(ERefC.target))
	  		{ 		 
		  		if((EMFUtils.getAttrValueByAttrName(ERefC.source,"ID_Pattern").toString().contains("-") == true)
		  			||  (EMFUtils.getAttrValueByAttrName(ERefC.target,"ID_Pattern").toString().contains("-") == true))
		  		{
		  			var AssocDef= 	
		  						"("+
		  						"create\t\t" + 
		  						createNodeNumber(ERefC.source)+
		  						"->" + 
		  						createNodeNumber(ERefC.target)+
		  						":"+
		  						ERefC.eReference.getName()+
		  						"),";
					edges.add(AssocDef);
		  		}
		  		else if(!ERefC.source.eClass().getName().toLowerCase().contains("domainspecificdiff"))
		  		{
		  			var AssocDef= 	
		  						"("+
		  						"preserve\t" + 
		  						createNodeNumber(ERefC.source)+
		  						"->" + 
		  						createNodeNumber(ERefC.target)+
		  						":"+
		  						ERefC.eReference.getName()+
		  						"),";
					edges.add(AssocDef);
		  		}
	  		}   		
		}
		if(edges.size()>0)	 
		{
	  		var s =edges.get(edges.size()-1);
	  		s= s.substring(0, s.length() - 1);
	  		edges.set(edges.size()-1,s);
		}
	  }

	 public Boolean addParamToRuleSignature(String param){
	  	if(param!=null && param!="" && !ruleSignature.contains(param)){
			if(ruleSignature!="" && ruleSignature!=null)
			 	{ ruleSignature += "," + param; }
			else 
			 	{ ruleSignature += param; }	
			return true;	
		}
		return false;	 	
	 }
	  
	 //***********************************************   
	 public String createNode(EObject n)
	 {
	 	return "node " + createNodeNumber(n);
	 }	 
	 
	 public String createNodeNumber(EObject n)
	 {
	 	return "n" + EMFUtils.getAttrValueByAttrName(n,"ID_Pattern").toString().replace("-","").trim();
	 }

	 //***********************************************   
	 public Stack<SrcRefTrgtMM> getAllAssocCollection_MM()
	 {	
	  	for(EClass node: nodes){
	  		var nodeAssocCollection = getAllNodeAssocCollection_MM(node);
	  		if(nodeAssocCollection.size()>0){
	  			allPathEdges.addAll(nodeAssocCollection);
	  		}	  		
	  	}
	  	
	  	return allPathEdges;
	 }
	  
	 public HashSet<SrcRefTrgtMM> getAllNodeAssocCollection_MM(EClass src)
	 {
	  	var allNodeAssociations = new HashSet<SrcRefTrgtMM>();		  	
		var features = new ArrayList<EStructuralFeature>(src.getEStructuralFeatures());
		for (EStructuralFeature r : features) {
			if(r instanceof  EReference){			
				  try{
					ArrayList<EClass>  AllTargets= EMFUtils.getAllTargetsMM(src,(EReference) r);
		  			
			  		if(AllTargets != null && AllTargets.size()>0){
				  		for (EClass target:AllTargets){
				  			SrcRefTrgtMM newERef= new SrcRefTrgtMM(src,(EReference) r,target);
				  			allNodeAssociations.add(newERef);
				  			var subClasses = EMFUtils.getAllSubClassesMM(target);
				  			for (EClass sc:subClasses){				  				
				  				SrcRefTrgtMM newERef2= new SrcRefTrgtMM(src,(EReference) r,sc);
				  				allNodeAssociations.add(newERef2);
				  			}				  			
				  		}
			  		}
		  		}catch(Exception ex){	  			
		  		}	  		
	  		}
	  	}
	  	return allNodeAssociations;
	 }	 
}








