<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="refactoring2WayDiffMM" nsURI="www.geodes.UdeM.edu/refactoring2WayDiffMM"
      nsPrefix="refactoring2WayDiffMM">
    <eClassifiers xsi:type="ecore:EClass" name="EAttribute">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="etype" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EClass">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="extends" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="implements" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eattributes" ordered="false"
          upperBound="-1" eType="#/0/EAttribute" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eoperations" ordered="false"
          upperBound="-1" eType="#/0/EOperation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ereferences" ordered="false"
          upperBound="-1" eType="#/0/EReference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="esupertypes" ordered="false"
          upperBound="-1" eType="#/0/EClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" ordered="false"
          upperBound="-1" eType="#/0/Interface"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nested_classes" ordered="false"
          upperBound="-1" eType="#/0/EClass" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nested_interfaces" ordered="false"
          upperBound="-1" eType="#/0/Interface" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="diffeattributes" upperBound="-1"
          eType="#/0/DiffEClass_eattributes" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="diffeoperations" upperBound="-1"
          eType="#/0/DiffEClass_eoperations" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="differeferences" upperBound="-1"
          eType="#/0/DiffEClass_ereferences" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="diffesupertypes" upperBound="-1"
          eType="#/0/DiffEClass_esupertypes" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="diffinterfaces" upperBound="-1"
          eType="#/0/DiffEClass_interfaces" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="diffnested_classes" upperBound="-1"
          eType="#/0/DiffEClass_nested_classes" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="diffnested_interfaces"
          upperBound="-1" eType="#/0/DiffEClass_nested_interfaces" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EOperation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="eparameters" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="etype" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="methodBody" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="__idKDM" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EPackage">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eclassifiers" ordered="false"
          upperBound="-1" eType="#/0/EClass" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="interfaces" ordered="false"
          upperBound="-1" eType="#/0/Interface" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="diffeclassifiers" upperBound="-1"
          eType="#/0/DiffEPackage_eclassifiers" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="diffinterfaces" upperBound="-1"
          eType="#/0/DiffEPackage_interfaces" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EReference">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="etype" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Interface">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="extends" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eoperations" ordered="false"
          upperBound="-1" eType="#/0/EOperation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="esupertypes" ordered="false"
          upperBound="-1" eType="#/0/Interface"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="diffeoperations" upperBound="-1"
          eType="#/0/DiffInterface_eoperations" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="diffesupertypes" upperBound="-1"
          eType="#/0/DiffInterface_esupertypes" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DiffKind">
      <eLiterals name="ADD" literal="ADD"/>
      <eLiterals name="DELETE" value="1" literal="DELETE"/>
      <eLiterals name="MODIFY" value="2" literal="MODIFY"/>
      <eLiterals name="NON" value="3" literal="NON"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SemanticObject" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffEAttribute"
          ordered="false" upperBound="-1" eType="#/0/DiffEAttribute"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffEClass"
          ordered="false" upperBound="-1" eType="#/0/DiffEClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffEClass_eattributes"
          ordered="false" upperBound="-1" eType="#/0/DiffEClass_eattributes"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffEClass_eoperations"
          ordered="false" upperBound="-1" eType="#/0/DiffEClass_eoperations"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffEClass_ereferences"
          ordered="false" upperBound="-1" eType="#/0/DiffEClass_ereferences"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffEClass_esupertypes"
          ordered="false" upperBound="-1" eType="#/0/DiffEClass_esupertypes"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffEClass_interfaces"
          ordered="false" upperBound="-1" eType="#/0/DiffEClass_interfaces"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffEClass_nested_classes"
          ordered="false" upperBound="-1" eType="#/0/DiffEClass_nested_classes"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffEClass_nested_interfaces"
          ordered="false" upperBound="-1" eType="#/0/DiffEClass_nested_interfaces"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffEOperation"
          ordered="false" upperBound="-1" eType="#/0/DiffEOperation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffEPackage"
          ordered="false" upperBound="-1" eType="#/0/DiffEPackage"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffEPackage_eclassifiers"
          ordered="false" upperBound="-1" eType="#/0/DiffEPackage_eclassifiers"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffEPackage_interfaces"
          ordered="false" upperBound="-1" eType="#/0/DiffEPackage_interfaces"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffEReference"
          ordered="false" upperBound="-1" eType="#/0/DiffEReference"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffInterface"
          ordered="false" upperBound="-1" eType="#/0/DiffInterface"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffInterface_eoperations"
          ordered="false" upperBound="-1" eType="#/0/DiffInterface_eoperations"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffInterface_esupertypes"
          ordered="false" upperBound="-1" eType="#/0/DiffInterface_esupertypes"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_EAttribute"
          ordered="false" upperBound="-1" eType="#/0/EAttribute"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_EClass"
          ordered="false" upperBound="-1" eType="#/0/EClass"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_EOperation"
          ordered="false" upperBound="-1" eType="#/0/EOperation"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_EPackage"
          ordered="false" upperBound="-1" eType="#/0/EPackage"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_EReference"
          ordered="false" upperBound="-1" eType="#/0/EReference"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_Interface"
          ordered="false" upperBound="-1" eType="#/0/Interface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SemanticDiff" eSuperTypes="#/0/SemanticObject"/>
    <eClassifiers xsi:type="ecore:EClass" name="SemanticConflict" eSuperTypes="#/0/SemanticObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="semanticdiffs" ordered="false"
          upperBound="-1" eType="#/0/SemanticDiff" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiffEAttribute" eSuperTypes="#/0/EAttribute">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" unique="false"
          lowerBound="1" eType="#/0/DiffKind" defaultValueLiteral="NON"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_name" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_etype" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiffEClass" eSuperTypes="#/0/EClass">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" unique="false"
          lowerBound="1" eType="#/0/DiffKind" defaultValueLiteral="NON"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_name" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_extends" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_implements" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_isAbstract" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_packageName" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiffEClass_eattributes">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" unique="false"
          lowerBound="1" eType="#/0/DiffKind" defaultValueLiteral="NON"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1"
          eType="#/0/EAttribute"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiffEClass_eoperations">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" unique="false"
          lowerBound="1" eType="#/0/DiffKind" defaultValueLiteral="NON"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1"
          eType="#/0/EOperation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiffEClass_ereferences">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" unique="false"
          lowerBound="1" eType="#/0/DiffKind" defaultValueLiteral="NON"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1"
          eType="#/0/EReference"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiffEClass_esupertypes">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" unique="false"
          lowerBound="1" eType="#/0/DiffKind" defaultValueLiteral="NON"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1"
          eType="#/0/EClass"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiffEClass_interfaces">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" unique="false"
          lowerBound="1" eType="#/0/DiffKind" defaultValueLiteral="NON"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1"
          eType="#/0/Interface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiffEClass_nested_classes">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" unique="false"
          lowerBound="1" eType="#/0/DiffKind" defaultValueLiteral="NON"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1"
          eType="#/0/EClass"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiffEClass_nested_interfaces">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" unique="false"
          lowerBound="1" eType="#/0/DiffKind" defaultValueLiteral="NON"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1"
          eType="#/0/Interface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiffEOperation" eSuperTypes="#/0/EOperation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" unique="false"
          lowerBound="1" eType="#/0/DiffKind" defaultValueLiteral="NON"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_name" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_eparameters" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_etype" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_methodBody" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiffEPackage" eSuperTypes="#/0/EPackage">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" unique="false"
          lowerBound="1" eType="#/0/DiffKind" defaultValueLiteral="NON"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_name" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiffEPackage_eclassifiers">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" unique="false"
          lowerBound="1" eType="#/0/DiffKind" defaultValueLiteral="NON"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1"
          eType="#/0/EClass"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiffEPackage_interfaces">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" unique="false"
          lowerBound="1" eType="#/0/DiffKind" defaultValueLiteral="NON"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1"
          eType="#/0/Interface"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiffEReference" eSuperTypes="#/0/EReference">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" unique="false"
          lowerBound="1" eType="#/0/DiffKind" defaultValueLiteral="NON"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_name" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_etype" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiffInterface" eSuperTypes="#/0/Interface">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" unique="false"
          lowerBound="1" eType="#/0/DiffKind" defaultValueLiteral="NON"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_name" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_extends" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_packageName" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiffInterface_eoperations">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" unique="false"
          lowerBound="1" eType="#/0/DiffKind" defaultValueLiteral="NON"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1"
          eType="#/0/EOperation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiffInterface_esupertypes">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" unique="false"
          lowerBound="1" eType="#/0/DiffKind" defaultValueLiteral="NON"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1"
          eType="#/0/Interface"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="refactoring2WayRuleMM" nsURI="www.geodes.UdeM.edu/refactoring2WayRuleMM"
      nsPrefix="refactoring2WayRuleMM">
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_EAttribute" eSuperTypes="#/0/EAttribute">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_EClass" eSuperTypes="#/0/EClass">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_EOperation" eSuperTypes="#/0/EOperation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_EPackage" eSuperTypes="#/0/EPackage">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_EReference" eSuperTypes="#/0/EReference">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_Interface" eSuperTypes="#/0/Interface">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_SemanticObject" abstract="true"
        eSuperTypes="#/0/SemanticObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_SemanticDiff" eSuperTypes="#/0/SemanticDiff">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_SemanticConflict" eSuperTypes="#/0/SemanticConflict">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffEAttribute" eSuperTypes="#/0/DiffEAttribute">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffEClass" eSuperTypes="#/0/DiffEClass">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffEClass_eattributes" eSuperTypes="#/0/DiffEClass_eattributes">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffEClass_eoperations" eSuperTypes="#/0/DiffEClass_eoperations">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffEClass_ereferences" eSuperTypes="#/0/DiffEClass_ereferences">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffEClass_esupertypes" eSuperTypes="#/0/DiffEClass_esupertypes">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffEClass_interfaces" eSuperTypes="#/0/DiffEClass_interfaces">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffEClass_nested_classes"
        eSuperTypes="#/0/DiffEClass_nested_classes">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffEClass_nested_interfaces"
        eSuperTypes="#/0/DiffEClass_nested_interfaces">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffEOperation" eSuperTypes="#/0/DiffEOperation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffEPackage" eSuperTypes="#/0/DiffEPackage">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffEPackage_eclassifiers"
        eSuperTypes="#/0/DiffEPackage_eclassifiers">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffEPackage_interfaces" eSuperTypes="#/0/DiffEPackage_interfaces">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffEReference" eSuperTypes="#/0/DiffEReference">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffInterface" eSuperTypes="#/0/DiffInterface">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffInterface_eoperations"
        eSuperTypes="#/0/DiffInterface_eoperations">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffInterface_esupertypes"
        eSuperTypes="#/0/DiffInterface_esupertypes">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Rule">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraints" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_DiffEAttribute"
          ordered="false" upperBound="-1" eType="#/0/DiffEAttribute" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_DiffEClass"
          ordered="false" upperBound="-1" eType="#/0/DiffEClass" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_DiffEClass_eattributes"
          ordered="false" upperBound="-1" eType="#/0/DiffEClass_eattributes" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_DiffEClass_eoperations"
          ordered="false" upperBound="-1" eType="#/0/DiffEClass_eoperations" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_DiffEClass_ereferences"
          ordered="false" upperBound="-1" eType="#/0/DiffEClass_ereferences" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_DiffEClass_esupertypes"
          ordered="false" upperBound="-1" eType="#/0/DiffEClass_esupertypes" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_DiffEClass_interfaces"
          ordered="false" upperBound="-1" eType="#/0/DiffEClass_interfaces" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_DiffEClass_nested_classes"
          ordered="false" upperBound="-1" eType="#/0/DiffEClass_nested_classes" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_DiffEClass_nested_interfaces"
          ordered="false" upperBound="-1" eType="#/0/DiffEClass_nested_interfaces"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_DiffEOperation"
          ordered="false" upperBound="-1" eType="#/0/DiffEOperation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_DiffEPackage"
          ordered="false" upperBound="-1" eType="#/0/DiffEPackage" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_DiffEPackage_eclassifiers"
          ordered="false" upperBound="-1" eType="#/0/DiffEPackage_eclassifiers" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_DiffEPackage_interfaces"
          ordered="false" upperBound="-1" eType="#/0/DiffEPackage_interfaces" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_DiffEReference"
          ordered="false" upperBound="-1" eType="#/0/DiffEReference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_DiffInterface"
          ordered="false" upperBound="-1" eType="#/0/DiffInterface" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_DiffInterface_eoperations"
          ordered="false" upperBound="-1" eType="#/0/DiffInterface_eoperations" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_DiffInterface_esupertypes"
          ordered="false" upperBound="-1" eType="#/0/DiffInterface_esupertypes" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_EAttribute"
          ordered="false" upperBound="-1" eType="#/0/EAttribute" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_EClass" ordered="false"
          upperBound="-1" eType="#/0/EClass" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_EOperation"
          ordered="false" upperBound="-1" eType="#/0/EOperation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_EPackage"
          ordered="false" upperBound="-1" eType="#/0/EPackage" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_EReference"
          ordered="false" upperBound="-1" eType="#/0/EReference" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_Interface"
          ordered="false" upperBound="-1" eType="#/0/Interface" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_SemanticObject"
          ordered="false" upperBound="-1" eType="#/0/SemanticObject" containment="true"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
