/**
 */
package refactoringDiffMM.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import refactoringDiffMM.util.RefactoringDiffMMAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class RefactoringDiffMMItemProviderAdapterFactory extends RefactoringDiffMMAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public RefactoringDiffMMItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.ConflictResolution} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ConflictResolutionItemProvider conflictResolutionItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.ConflictResolution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createConflictResolutionAdapter() {
		if (conflictResolutionItemProvider == null) {
			conflictResolutionItemProvider = new ConflictResolutionItemProvider(this);
		}

		return conflictResolutionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.DiffEAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffEAttributeItemProvider diffEAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.DiffEAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffEAttributeAdapter() {
		if (diffEAttributeItemProvider == null) {
			diffEAttributeItemProvider = new DiffEAttributeItemProvider(this);
		}

		return diffEAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.DiffEClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffEClassItemProvider diffEClassItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.DiffEClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffEClassAdapter() {
		if (diffEClassItemProvider == null) {
			diffEClassItemProvider = new DiffEClassItemProvider(this);
		}

		return diffEClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.DiffEClass_eattributes} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffEClass_eattributesItemProvider diffEClass_eattributesItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.DiffEClass_eattributes}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffEClass_eattributesAdapter() {
		if (diffEClass_eattributesItemProvider == null) {
			diffEClass_eattributesItemProvider = new DiffEClass_eattributesItemProvider(this);
		}

		return diffEClass_eattributesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.DiffEClass_eoperations} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffEClass_eoperationsItemProvider diffEClass_eoperationsItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.DiffEClass_eoperations}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffEClass_eoperationsAdapter() {
		if (diffEClass_eoperationsItemProvider == null) {
			diffEClass_eoperationsItemProvider = new DiffEClass_eoperationsItemProvider(this);
		}

		return diffEClass_eoperationsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.DiffEClass_ereferences} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffEClass_ereferencesItemProvider diffEClass_ereferencesItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.DiffEClass_ereferences}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffEClass_ereferencesAdapter() {
		if (diffEClass_ereferencesItemProvider == null) {
			diffEClass_ereferencesItemProvider = new DiffEClass_ereferencesItemProvider(this);
		}

		return diffEClass_ereferencesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.DiffEClass_esupertypes} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffEClass_esupertypesItemProvider diffEClass_esupertypesItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.DiffEClass_esupertypes}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffEClass_esupertypesAdapter() {
		if (diffEClass_esupertypesItemProvider == null) {
			diffEClass_esupertypesItemProvider = new DiffEClass_esupertypesItemProvider(this);
		}

		return diffEClass_esupertypesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.DiffEClass_interfaces} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffEClass_interfacesItemProvider diffEClass_interfacesItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.DiffEClass_interfaces}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffEClass_interfacesAdapter() {
		if (diffEClass_interfacesItemProvider == null) {
			diffEClass_interfacesItemProvider = new DiffEClass_interfacesItemProvider(this);
		}

		return diffEClass_interfacesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.DiffEClass_nested_classes} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffEClass_nested_classesItemProvider diffEClass_nested_classesItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.DiffEClass_nested_classes}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffEClass_nested_classesAdapter() {
		if (diffEClass_nested_classesItemProvider == null) {
			diffEClass_nested_classesItemProvider = new DiffEClass_nested_classesItemProvider(this);
		}

		return diffEClass_nested_classesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.DiffEClass_nested_interfaces} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffEClass_nested_interfacesItemProvider diffEClass_nested_interfacesItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.DiffEClass_nested_interfaces}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffEClass_nested_interfacesAdapter() {
		if (diffEClass_nested_interfacesItemProvider == null) {
			diffEClass_nested_interfacesItemProvider = new DiffEClass_nested_interfacesItemProvider(this);
		}

		return diffEClass_nested_interfacesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.DiffEOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffEOperationItemProvider diffEOperationItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.DiffEOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffEOperationAdapter() {
		if (diffEOperationItemProvider == null) {
			diffEOperationItemProvider = new DiffEOperationItemProvider(this);
		}

		return diffEOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.DiffEPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffEPackageItemProvider diffEPackageItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.DiffEPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffEPackageAdapter() {
		if (diffEPackageItemProvider == null) {
			diffEPackageItemProvider = new DiffEPackageItemProvider(this);
		}

		return diffEPackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.DiffEPackage_eclassifiers} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffEPackage_eclassifiersItemProvider diffEPackage_eclassifiersItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.DiffEPackage_eclassifiers}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffEPackage_eclassifiersAdapter() {
		if (diffEPackage_eclassifiersItemProvider == null) {
			diffEPackage_eclassifiersItemProvider = new DiffEPackage_eclassifiersItemProvider(this);
		}

		return diffEPackage_eclassifiersItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.DiffEPackage_interfaces} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffEPackage_interfacesItemProvider diffEPackage_interfacesItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.DiffEPackage_interfaces}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffEPackage_interfacesAdapter() {
		if (diffEPackage_interfacesItemProvider == null) {
			diffEPackage_interfacesItemProvider = new DiffEPackage_interfacesItemProvider(this);
		}

		return diffEPackage_interfacesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.DiffEPackage_test} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffEPackage_testItemProvider diffEPackage_testItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.DiffEPackage_test}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffEPackage_testAdapter() {
		if (diffEPackage_testItemProvider == null) {
			diffEPackage_testItemProvider = new DiffEPackage_testItemProvider(this);
		}

		return diffEPackage_testItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.DiffEReference} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffEReferenceItemProvider diffEReferenceItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.DiffEReference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffEReferenceAdapter() {
		if (diffEReferenceItemProvider == null) {
			diffEReferenceItemProvider = new DiffEReferenceItemProvider(this);
		}

		return diffEReferenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.DiffInterface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffInterfaceItemProvider diffInterfaceItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.DiffInterface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffInterfaceAdapter() {
		if (diffInterfaceItemProvider == null) {
			diffInterfaceItemProvider = new DiffInterfaceItemProvider(this);
		}

		return diffInterfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.DiffInterface_eoperations} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffInterface_eoperationsItemProvider diffInterface_eoperationsItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.DiffInterface_eoperations}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffInterface_eoperationsAdapter() {
		if (diffInterface_eoperationsItemProvider == null) {
			diffInterface_eoperationsItemProvider = new DiffInterface_eoperationsItemProvider(this);
		}

		return diffInterface_eoperationsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.DiffInterface_esupertypes} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DiffInterface_esupertypesItemProvider diffInterface_esupertypesItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.DiffInterface_esupertypes}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDiffInterface_esupertypesAdapter() {
		if (diffInterface_esupertypesItemProvider == null) {
			diffInterface_esupertypesItemProvider = new DiffInterface_esupertypesItemProvider(this);
		}

		return diffInterface_esupertypesItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.DifftestAssociations} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DifftestAssociationsItemProvider difftestAssociationsItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.DifftestAssociations}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDifftestAssociationsAdapter() {
		if (difftestAssociationsItemProvider == null) {
			difftestAssociationsItemProvider = new DifftestAssociationsItemProvider(this);
		}

		return difftestAssociationsItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.DifftestAssociations_multi} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DifftestAssociations_multiItemProvider difftestAssociations_multiItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.DifftestAssociations_multi}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDifftestAssociations_multiAdapter() {
		if (difftestAssociations_multiItemProvider == null) {
			difftestAssociations_multiItemProvider = new DifftestAssociations_multiItemProvider(this);
		}

		return difftestAssociations_multiItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.DifftestAssociations_single} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DifftestAssociations_singleItemProvider difftestAssociations_singleItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.DifftestAssociations_single}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDifftestAssociations_singleAdapter() {
		if (difftestAssociations_singleItemProvider == null) {
			difftestAssociations_singleItemProvider = new DifftestAssociations_singleItemProvider(this);
		}

		return difftestAssociations_singleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.EAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EAttributeItemProvider eAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.EAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEAttributeAdapter() {
		if (eAttributeItemProvider == null) {
			eAttributeItemProvider = new EAttributeItemProvider(this);
		}

		return eAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.EClass} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EClassItemProvider eClassItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.EClass}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEClassAdapter() {
		if (eClassItemProvider == null) {
			eClassItemProvider = new EClassItemProvider(this);
		}

		return eClassItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.EOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EOperationItemProvider eOperationItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.EOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEOperationAdapter() {
		if (eOperationItemProvider == null) {
			eOperationItemProvider = new EOperationItemProvider(this);
		}

		return eOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.EPackage} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EPackageItemProvider ePackageItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.EPackage}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEPackageAdapter() {
		if (ePackageItemProvider == null) {
			ePackageItemProvider = new EPackageItemProvider(this);
		}

		return ePackageItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.EReference} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EReferenceItemProvider eReferenceItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.EReference}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createEReferenceAdapter() {
		if (eReferenceItemProvider == null) {
			eReferenceItemProvider = new EReferenceItemProvider(this);
		}

		return eReferenceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.Interface} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected InterfaceItemProvider interfaceItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.Interface}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createInterfaceAdapter() {
		if (interfaceItemProvider == null) {
			interfaceItemProvider = new InterfaceItemProvider(this);
		}

		return interfaceItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.SemanticConflict} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SemanticConflictItemProvider semanticConflictItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.SemanticConflict}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSemanticConflictAdapter() {
		if (semanticConflictItemProvider == null) {
			semanticConflictItemProvider = new SemanticConflictItemProvider(this);
		}

		return semanticConflictItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.SemanticDiff} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SemanticDiffItemProvider semanticDiffItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.SemanticDiff}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSemanticDiffAdapter() {
		if (semanticDiffItemProvider == null) {
			semanticDiffItemProvider = new SemanticDiffItemProvider(this);
		}

		return semanticDiffItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link refactoringDiffMM.testAssociations} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected testAssociationsItemProvider testAssociationsItemProvider;

	/**
	 * This creates an adapter for a {@link refactoringDiffMM.testAssociations}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createtestAssociationsAdapter() {
		if (testAssociationsItemProvider == null) {
			testAssociationsItemProvider = new testAssociationsItemProvider(this);
		}

		return testAssociationsItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (conflictResolutionItemProvider != null) conflictResolutionItemProvider.dispose();
		if (diffEAttributeItemProvider != null) diffEAttributeItemProvider.dispose();
		if (diffEClassItemProvider != null) diffEClassItemProvider.dispose();
		if (diffEClass_eattributesItemProvider != null) diffEClass_eattributesItemProvider.dispose();
		if (diffEClass_eoperationsItemProvider != null) diffEClass_eoperationsItemProvider.dispose();
		if (diffEClass_ereferencesItemProvider != null) diffEClass_ereferencesItemProvider.dispose();
		if (diffEClass_esupertypesItemProvider != null) diffEClass_esupertypesItemProvider.dispose();
		if (diffEClass_interfacesItemProvider != null) diffEClass_interfacesItemProvider.dispose();
		if (diffEClass_nested_classesItemProvider != null) diffEClass_nested_classesItemProvider.dispose();
		if (diffEClass_nested_interfacesItemProvider != null) diffEClass_nested_interfacesItemProvider.dispose();
		if (diffEOperationItemProvider != null) diffEOperationItemProvider.dispose();
		if (diffEPackageItemProvider != null) diffEPackageItemProvider.dispose();
		if (diffEPackage_eclassifiersItemProvider != null) diffEPackage_eclassifiersItemProvider.dispose();
		if (diffEPackage_interfacesItemProvider != null) diffEPackage_interfacesItemProvider.dispose();
		if (diffEPackage_testItemProvider != null) diffEPackage_testItemProvider.dispose();
		if (diffEReferenceItemProvider != null) diffEReferenceItemProvider.dispose();
		if (diffInterfaceItemProvider != null) diffInterfaceItemProvider.dispose();
		if (diffInterface_eoperationsItemProvider != null) diffInterface_eoperationsItemProvider.dispose();
		if (diffInterface_esupertypesItemProvider != null) diffInterface_esupertypesItemProvider.dispose();
		if (difftestAssociationsItemProvider != null) difftestAssociationsItemProvider.dispose();
		if (difftestAssociations_multiItemProvider != null) difftestAssociations_multiItemProvider.dispose();
		if (difftestAssociations_singleItemProvider != null) difftestAssociations_singleItemProvider.dispose();
		if (eAttributeItemProvider != null) eAttributeItemProvider.dispose();
		if (eClassItemProvider != null) eClassItemProvider.dispose();
		if (eOperationItemProvider != null) eOperationItemProvider.dispose();
		if (ePackageItemProvider != null) ePackageItemProvider.dispose();
		if (eReferenceItemProvider != null) eReferenceItemProvider.dispose();
		if (interfaceItemProvider != null) interfaceItemProvider.dispose();
		if (semanticConflictItemProvider != null) semanticConflictItemProvider.dispose();
		if (semanticDiffItemProvider != null) semanticDiffItemProvider.dispose();
		if (testAssociationsItemProvider != null) testAssociationsItemProvider.dispose();
	}

}
