<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dssmmDiffMM" nsURI="http://www.zadahmad.org/dsvcs/dssmmDiffMM"
    nsPrefix="dssmmDiffMM">
  <eClassifiers xsi:type="ecore:EClass" name="DecisionSupport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="model" eType="#//Model"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1"
        eType="#//Option" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vendors" upperBound="-1"
        eType="#//Vendor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffmodel" upperBound="-1"
        eType="#//DiffDecisionSupport_model" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffoptions" upperBound="-1"
        eType="#//DiffDecisionSupport_options" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffvendors" upperBound="-1"
        eType="#//DiffDecisionSupport_vendors" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Model">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ModelID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Goal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Descr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NumFacts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rootFactor" eType="#//Factor"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffrootFactor" upperBound="-1"
        eType="#//DiffModel_rootFactor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Factor" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FactorID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Descr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GW" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LW" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Del" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HideOnLine" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scores" upperBound="-1"
        eType="#//Score" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Hierarchy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MasterFactorID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffscores" upperBound="-1"
        eType="#//DiffFactor_scores" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LeafFactor" eSuperTypes="#//Factor"/>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeFactor" eSuperTypes="#//Factor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subFactors" upperBound="-1"
        eType="#//Factor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffsubFactors" upperBound="-1"
        eType="#//DiffCompositeFactor_subFactors" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Option">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OptionID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Sort" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Cost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NumOtherCosts" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vendor" eType="#//Vendor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffvendor" upperBound="-1"
        eType="#//DiffOption_vendor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vendor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VendorID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Score">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SScore" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Standard Score 0-100 and is the one used for all calculations&#xD;&#xA;&#xD;&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DScore" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="In the case of a verbal or List method this is the verbal method definition index. In the case of numeric methods it is the actual numeric value.&#xD;&#xA;&#xD;&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Descr" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Comment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="score_option" eType="#//Option"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MethodID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diffscore_option" upperBound="-1"
        eType="#//DiffScore_score_option" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ClassDiffKind">
    <eLiterals name="ADD" literal="ADD"/>
    <eLiterals name="DELETE" value="1" literal="DELETE"/>
    <eLiterals name="MODIFY" value="2" literal="MODIFY"/>
    <eLiterals name="NON" value="3" literal="NON"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AscDiffKind">
    <eLiterals name="ADD" literal="ADD"/>
    <eLiterals name="DELETE" value="1" literal="DELETE"/>
    <eLiterals name="NON" value="2" literal="NON"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AUTHOR">
    <eLiterals name="LEFT" literal="LEFT"/>
    <eLiterals name="RIGHT" value="1" literal="RIGHT"/>
    <eLiterals name="EQUAL" value="2" literal="EQUAL"/>
    <eLiterals name="MIXED" value="3" literal="MIXED"/>
    <eLiterals name="NON" value="4" literal="NON"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ChangeStatus">
    <eLiterals name="EQUIVALENT" literal="EQUIVALENT"/>
    <eLiterals name="CONTRADICTING" value="1" literal="CONTRADICTING"/>
    <eLiterals name="NON" value="2" literal="NON"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SemanticObject" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DecisionSupport"
        upperBound="-1" eType="#//DecisionSupport"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffCompositeFactor_subFactors"
        upperBound="-1" eType="#//DiffCompositeFactor_subFactors"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffDecisionSupport_model"
        upperBound="-1" eType="#//DiffDecisionSupport_model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffDecisionSupport_options"
        upperBound="-1" eType="#//DiffDecisionSupport_options"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffDecisionSupport_vendors"
        upperBound="-1" eType="#//DiffDecisionSupport_vendors"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffFactor_scores"
        upperBound="-1" eType="#//DiffFactor_scores"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffModel_rootFactor"
        upperBound="-1" eType="#//DiffModel_rootFactor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffOption_vendor"
        upperBound="-1" eType="#//DiffOption_vendor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffScore_score_option"
        upperBound="-1" eType="#//DiffScore_score_option"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_Factor"
        upperBound="-1" eType="#//Factor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_Model" upperBound="-1"
        eType="#//Model"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_Option"
        upperBound="-1" eType="#//Option"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_Score" upperBound="-1"
        eType="#//Score"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_Vendor"
        upperBound="-1" eType="#//Vendor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SemanticDiff" eSuperTypes="#//SemanticObject">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" unique="false"
        lowerBound="1" eType="#//AUTHOR" defaultValueLiteral="NON"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SemanticConflict" eSuperTypes="#//SemanticObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="semanticdiffs" upperBound="-1"
        eType="#//SemanticDiff" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffDecisionSupport" eSuperTypes="#//DecisionSupport">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//ClassDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//ClassDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Name_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Name_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NameChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffDecisionSupport_model">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//AscDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//AscDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Model"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffDecisionSupport_options">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//AscDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//AscDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Option"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffDecisionSupport_vendors">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//AscDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//AscDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Vendor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffModel" eSuperTypes="#//Model">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//ClassDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//ClassDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_ModelID_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_ModelID_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ModelIDChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Name_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Name_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NameChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Goal_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Goal_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GoalChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Descr_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Descr_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DescrChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_NumFacts_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_NumFacts_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NumFactsChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffModel_rootFactor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//AscDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//AscDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Factor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffFactor_scores">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//AscDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//AscDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Score"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffLeafFactor" eSuperTypes="#//LeafFactor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//ClassDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//ClassDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_FactorID_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_FactorID_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FactorIDChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Name_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Name_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NameChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Descr_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Descr_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DescrChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_GW_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_GW_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GWChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_LW_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_LW_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LWChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Del_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Del_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DelChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_HideOnLine_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_HideOnLine_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HideOnLineChangeStatus"
        unique="false" lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Hierarchy_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Hierarchy_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HierarchyChangeStatus"
        unique="false" lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_MasterFactorID_Left"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_MasterFactorID_Right"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MasterFactorIDChangeStatus"
        unique="false" lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffCompositeFactor" eSuperTypes="#//CompositeFactor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//ClassDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//ClassDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_FactorID_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_FactorID_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="FactorIDChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Name_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Name_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NameChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Descr_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Descr_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DescrChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_GW_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_GW_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="GWChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_LW_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_LW_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="LWChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Del_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Del_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DelChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_HideOnLine_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_HideOnLine_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HideOnLineChangeStatus"
        unique="false" lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Hierarchy_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Hierarchy_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="HierarchyChangeStatus"
        unique="false" lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_MasterFactorID_Left"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_MasterFactorID_Right"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MasterFactorIDChangeStatus"
        unique="false" lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffCompositeFactor_subFactors">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//AscDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//AscDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Factor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffOption" eSuperTypes="#//Option">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//ClassDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//ClassDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_OptionID_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_OptionID_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="OptionIDChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Name_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Name_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NameChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Sort_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Sort_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SortChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Cost_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Cost_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CostChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_NumOtherCosts_Left"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_NumOtherCosts_Right"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NumOtherCostsChangeStatus"
        unique="false" lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Description_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Description_Right"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DescriptionChangeStatus"
        unique="false" lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffOption_vendor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//AscDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//AscDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Vendor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffVendor" eSuperTypes="#//Vendor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//ClassDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//ClassDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_VendorID_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_VendorID_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VendorIDChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Name_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Name_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="NameChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Description_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Description_Right"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DescriptionChangeStatus"
        unique="false" lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffScore" eSuperTypes="#//Score">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//ClassDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//ClassDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_SScore_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_SScore_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="SScoreChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_DScore_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_DScore_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DScoreChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Descr_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Descr_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DescrChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Comment_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_Comment_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CommentChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_MethodID_Left" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_MethodID_Right" unique="false"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MethodIDChangeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiffScore_score_option">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Left" unique="false"
        lowerBound="1" eType="#//AscDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind_Right" unique="false"
        lowerBound="1" eType="#//AscDiffKind" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="changeStatus" unique="false"
        lowerBound="1" eType="#//ChangeStatus" defaultValueLiteral="NON"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1" eType="#//Option"/>
  </eClassifiers>
</ecore:EPackage>
