<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="petrinets2WayDiffMM" nsURI="www.geodes.UdeM.edu/petrinets2WayDiffMM"
      nsPrefix="petrinets2WayDiffMM">
    <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PetriNet" eSuperTypes="#/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="places" upperBound="-1"
          eType="#/0/Place" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
          eType="#/0/Transition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="diffplaces" upperBound="-1"
          eType="#/0/DiffPetriNet_places" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="difftransitions" upperBound="-1"
          eType="#/0/DiffPetriNet_transitions" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Place" eSuperTypes="#/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tokens" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" upperBound="-1"
          eType="#/0/Transition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="difftransitions" upperBound="-1"
          eType="#/0/DiffPlace_transitions" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Transition" eSuperTypes="#/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="places" upperBound="-1"
          eType="#/0/Place"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="diffplaces" upperBound="-1"
          eType="#/0/DiffTransition_places" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="DiffKind">
      <eLiterals name="NON" literal="NON"/>
      <eLiterals name="ADD" value="1" literal="ADD"/>
      <eLiterals name="DELETE" value="2" literal="DELETE"/>
      <eLiterals name="MODIFY" value="3" literal="MODIFY"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SemanticObject" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false"
          unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffPetriNet"
          ordered="false" upperBound="-1" eType="#/0/DiffPetriNet"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffPetriNet_places"
          ordered="false" upperBound="-1" eType="#/0/DiffPetriNet_places"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffPetriNet_transitions"
          ordered="false" upperBound="-1" eType="#/0/DiffPetriNet_transitions"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffPlace"
          ordered="false" upperBound="-1" eType="#/0/DiffPlace"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffPlace_transitions"
          ordered="false" upperBound="-1" eType="#/0/DiffPlace_transitions"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffTransition"
          ordered="false" upperBound="-1" eType="#/0/DiffTransition"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_DiffTransition_places"
          ordered="false" upperBound="-1" eType="#/0/DiffTransition_places"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="SemanticObject_NamedElement"
          ordered="false" upperBound="-1" eType="#/0/NamedElement"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SemanticDiff" eSuperTypes="#/0/SemanticObject"/>
    <eClassifiers xsi:type="ecore:EClass" name="SemanticConflict" eSuperTypes="#/0/SemanticObject">
      <eStructuralFeatures xsi:type="ecore:EReference" name="semanticdiffs" ordered="false"
          upperBound="-1" eType="#/0/SemanticDiff"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiffPetriNet" eSuperTypes="#/0/PetriNet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" unique="false"
          lowerBound="1" eType="#/0/DiffKind" defaultValueLiteral="NON"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_id" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_name" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiffPetriNet_places">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" unique="false"
          lowerBound="1" eType="#/0/DiffKind" defaultValueLiteral="NON"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1"
          eType="#/0/Place"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiffPetriNet_transitions">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" unique="false"
          lowerBound="1" eType="#/0/DiffKind" defaultValueLiteral="NON"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1"
          eType="#/0/Transition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiffPlace" eSuperTypes="#/0/Place">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" unique="false"
          lowerBound="1" eType="#/0/DiffKind" defaultValueLiteral="NON"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_id" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_name" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_tokens" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiffPlace_transitions">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" unique="false"
          lowerBound="1" eType="#/0/DiffKind" defaultValueLiteral="NON"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1"
          eType="#/0/Transition"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiffTransition" eSuperTypes="#/0/Transition">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" unique="false"
          lowerBound="1" eType="#/0/DiffKind" defaultValueLiteral="NON"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_id" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="new_name" unique="false"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DiffTransition_places">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="diff_kind" unique="false"
          lowerBound="1" eType="#/0/DiffKind" defaultValueLiteral="NON"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eType" lowerBound="1"
          eType="#/0/Place"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="petrinets2WayRuleMM" nsURI="www.geodes.UdeM.edu/petrinets2WayRuleMM"
      nsPrefix="petrinets2WayRuleMM">
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_NamedElement" abstract="true"
        eSuperTypes="#/0/NamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_PetriNet" eSuperTypes="#/0/PetriNet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_Place" eSuperTypes="#/0/Place">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_Transition" eSuperTypes="#/0/Transition">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_SemanticObject" abstract="true"
        eSuperTypes="#/0/SemanticObject">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_SemanticDiff" eSuperTypes="#/0/SemanticDiff">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_SemanticConflict" eSuperTypes="#/0/SemanticConflict">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffPetriNet" eSuperTypes="#/0/DiffPetriNet">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffPetriNet_places" eSuperTypes="#/0/DiffPetriNet_places">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffPetriNet_transitions"
        eSuperTypes="#/0/DiffPetriNet_transitions">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffPlace" eSuperTypes="#/0/DiffPlace">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffPlace_transitions" eSuperTypes="#/0/DiffPlace_transitions">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffTransition" eSuperTypes="#/0/DiffTransition">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Pattern_DiffTransition_places" eSuperTypes="#/0/DiffTransition_places">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID_Pattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isForbidden" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Rule">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraints" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_DiffPetriNet"
          ordered="false" upperBound="-1" eType="#/0/DiffPetriNet" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_DiffPetriNet_places"
          ordered="false" upperBound="-1" eType="#/0/DiffPetriNet_places" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_DiffPetriNet_transitions"
          ordered="false" upperBound="-1" eType="#/0/DiffPetriNet_transitions" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_DiffPlace"
          ordered="false" upperBound="-1" eType="#/0/DiffPlace" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_DiffPlace_transitions"
          ordered="false" upperBound="-1" eType="#/0/DiffPlace_transitions" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_DiffTransition"
          ordered="false" upperBound="-1" eType="#/0/DiffTransition" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_DiffTransition_places"
          ordered="false" upperBound="-1" eType="#/0/DiffTransition_places" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_NamedElement"
          ordered="false" upperBound="-1" eType="#/0/NamedElement" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rulePattern_SemanticObject"
          ordered="false" upperBound="-1" eType="#/0/SemanticObject" containment="true"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
